-- ============================================
-- ReptiCube Tracker — Species Database Migration
-- Run this AFTER the main schema.sql, in Supabase SQL Editor.
-- ============================================

create table if not exists public.species (
  id text primary key,                        -- slug e.g. 'ball-python'
  common_name text not null,
  scientific_name text not null,
  category text not null check (category in ('snake', 'lizard', 'gecko', 'tortoise', 'other')),
  origin text,                                -- "West/Central Africa"
  adult_size text,                            -- "1.2-1.5m (females larger)"
  lifespan text,                              -- "20-30 years"

  -- Temperatures (Celsius)
  temp_basking text,                          -- "32-35°C"
  temp_warm text,                             -- "29-31°C"
  temp_cool text,                             -- "24-26°C"
  temp_night text,                            -- "22-25°C (no drop below 21°C)"

  humidity text,                              -- "55-65%, 70%+ during shed"
  enclosure_size text,                        -- "120x60x60cm minimum for adult"
  substrate text,                             -- "Cypress mulch, aspen, coconut fibre"
  lighting text,                              -- "12h day/night cycle, low UVB optional"

  diet text,                                  -- "Appropriately sized rodents"
  feeding_schedule text,                      -- "Juvenile: weekly. Adult: every 10-14 days"
  prey_size_guide text,                       -- "Prey 1-1.25x widest body width"

  handling text,                              -- "Tolerates handling. Avoid 48h post-feed"
  temperament text,                           -- "Docile, may ball up when stressed"

  health_notes text,                          -- "Prone to RI from low temps. Mites common"
  common_issues text,                         -- "Refused feeding, scale rot, stuck shed"

  difficulty text check (difficulty in ('beginner', 'intermediate', 'advanced', 'expert')),

  notes text,                                 -- catch-all
  created_at timestamptz not null default now()
);

create index if not exists idx_species_common on public.species(common_name);
create index if not exists idx_species_category on public.species(category);

-- Public read access for species (everyone can browse)
alter table public.species enable row level security;
create policy "Anyone can view species" on public.species
  for select using (true);

-- ============================================
-- SEED DATA — ~100 species
-- Compiled from general husbandry knowledge.
-- REVIEW EACH ENTRY before trusting for your animals.
-- ============================================

-- SNAKES (Pythons)
insert into public.species (id, common_name, scientific_name, category, origin, adult_size, lifespan, temp_basking, temp_warm, temp_cool, temp_night, humidity, enclosure_size, substrate, lighting, diet, feeding_schedule, prey_size_guide, handling, temperament, health_notes, common_issues, difficulty) values
('ball-python', 'Ball Python', 'Python regius', 'snake', 'West/Central Africa (savanna, forest edges)', '1.2-1.5m, females larger and heavier', '20-30+ years', '32-35°C', '29-31°C', '24-26°C', '22-25°C (do not drop below 21°C)', '55-65%, raise to 70%+ during shed', 'Adult: 120x60x60cm minimum. Juvenile: smaller, more enclosed', 'Cypress mulch, aspen shavings, coconut fibre — avoid pine/cedar', '12h light cycle. Low UVB (5%) optional but beneficial', 'Appropriately sized rodents (mice, rats)', 'Juvenile (<400g): weekly. Sub-adult: every 7-10 days. Adult: every 10-14 days', 'Prey 1-1.25x the widest part of body', 'Tolerates handling well. Wait 48h after feeding. Limit sessions to 15-20 min', 'Generally docile. May ball up defensively. Rarely bites — better strategy is to hide', 'Susceptible to respiratory infections from low temps/high humidity combo. Mites common from poor husbandry', 'Refused feeding (very common, especially seasonal), stuck sheds, scale rot from wet substrate', 'beginner'),

('burmese-python', 'Burmese Python', 'Python bivittatus', 'snake', 'Southeast Asia', '3.5-5m, females reach 6m+', '20-25 years', '32-35°C', '29-32°C', '24-27°C', '23-25°C', '60-70%', 'Massive: 2.5m+ enclosure for adult. Custom rooms often needed', 'Newspaper, aspen, cypress', '12h cycle, UVB beneficial', 'Large rodents, rabbits, eventually small ungulates for breeders', 'Hatchling: weekly. Juvenile: every 10 days. Adult: every 2-4 weeks', 'Prey ~1-1.5x body width', 'NEVER handle alone over 2m. Two people minimum for large adults. Powerful constrictors', 'Generally calm but unpredictable. Powerful strike + constriction', 'Respiratory infections, obesity in adults, IBD risk', 'Mouth rot, scale rot, refused feeding in winter', 'expert'),

('reticulated-python', 'Reticulated Python', 'Malayopython reticulatus', 'snake', 'Southeast Asia', '3-6m, occasionally larger', '15-25 years', '32-35°C', '29-32°C', '24-27°C', '23-25°C', '70-80%', '2.5m+ for adult, more for large specimens', 'Cypress mulch, large bark', '12h cycle, UVB recommended', 'Rodents to rabbits/poultry', 'Juvenile: weekly. Adult: every 2-3 weeks', '1-1.5x body width', 'Two-person minimum for adults. Highly intelligent and food-driven', 'Variable — some docile, others very defensive. Fast strike', 'Generally hardy. RI risk if temps drop', 'Aggressive feeding response, stuck shed', 'expert'),

('carpet-python', 'Carpet Python', 'Morelia spilota', 'snake', 'Australia, New Guinea', '1.8-2.5m depending on subspecies', '15-30 years', '32-35°C', '28-31°C', '23-26°C', '20-23°C', '50-60%', '180x60x60cm for adult, arboreal so height matters', 'Cypress, aspen, bark', '12h cycle, UVB beneficial', 'Rodents — quail/chicks for larger adults', 'Juvenile: weekly. Adult: every 2-3 weeks', '1-1.25x body width', 'Tolerates handling. Watch for defensive strikes from juveniles', 'Juveniles often nippy, mellow with age. Active especially at night', 'Hardy species. Watch for parasites in imports', 'Stuck shed if humidity too low, RI if too damp', 'intermediate'),

('green-tree-python', 'Green Tree Python', 'Morelia viridis', 'snake', 'New Guinea, Indonesia, Cape York Australia', '1.5-2m', '15-20 years', '30-32°C basking branch', '28-30°C', '24-26°C', '22-24°C', '70-85%', 'Arboreal: 90x60x90cm minimum (tall)', 'Sphagnum moss, coconut fibre — high humidity substrate', '12h cycle, low UVB', 'Rodents', 'Juvenile: weekly. Adult: every 10-14 days', 'Slightly smaller than body width (smaller meals more frequent)', 'Minimal handling. Display species. Will strike defensively', 'Defensive, beautiful display animal. Do not co-habitate', 'Sensitive to husbandry mistakes. RI common with bad ventilation', 'Stuck shed, refused feeding, scale damage from rough perches', 'advanced'),

('blood-python', 'Blood Python', 'Python brongersmai', 'snake', 'Southeast Asia (Sumatra, Malaysia)', '1.2-1.8m, very heavy-bodied', '20-25 years', '30-32°C', '27-30°C', '23-25°C', '22-24°C', '60-70%, raise during shed', '120x60x45cm for adult', 'Cypress mulch, coconut fibre', '12h cycle, UVB optional', 'Rodents, larger prey for big adults', 'Juvenile: weekly. Adult: every 2-3 weeks', '1-1.25x body width', 'Variable temperament. Some calm, some defensive. Slow but powerful strike', 'Reputation for being snappy but improving with captive-bred animals', 'Prone to obesity. RI risk', 'Mouth rot, mites in imports', 'intermediate'),

('boa-imperator', 'Common Boa / Boa Imperator', 'Boa imperator', 'snake', 'Central America', '1.5-2.5m, females larger', '20-30 years', '32-35°C', '29-31°C', '24-26°C', '22-24°C', '50-60%', '180x60x60cm for adult', 'Cypress mulch, aspen', '12h cycle, UVB beneficial', 'Rodents', 'Juvenile: weekly. Adult: every 2-4 weeks (avoid overfeeding)', '1-1.25x body width', 'Generally tolerates handling well. Wait 72h after feeding', 'Mostly calm. Powerful constrictor — never let coil neck', 'IBD (Inclusion Body Disease) — quarantine new animals. Obesity from overfeeding', 'Obesity, mouth rot, mites', 'intermediate'),

('red-tail-boa', 'Red-Tailed Boa', 'Boa constrictor constrictor', 'snake', 'South America', '2-3m, occasionally larger', '20-30 years', '32-35°C', '29-31°C', '24-26°C', '22-24°C', '55-65%', '210x90x90cm for adult', 'Cypress mulch', '12h cycle, UVB recommended', 'Rodents, rabbits for large adults', 'Juvenile: weekly. Adult: every 2-4 weeks', '1-1.25x body width', 'Two-person handling for adults', 'Generally docile but more aggressive than imperator. Powerful', 'IBD risk, obesity', 'Stuck shed, mouth rot', 'intermediate'),

('corn-snake', 'Corn Snake', 'Pantherophis guttatus', 'snake', 'Southeastern USA', '90-180cm', '15-23 years', '29-32°C', '26-29°C', '22-24°C', '20-22°C', '40-50%', '120x45x45cm for adult', 'Aspen shavings, cypress mulch', '12h cycle, no UVB needed but beneficial', 'Mice (most adults take medium/large adult mice)', 'Juvenile: weekly. Adult: every 7-10 days', '1-1.25x body width', 'Excellent for handling. Active, fast. Wait 48h after feeding', 'Curious, active, generally docile. Great beginner species', 'Hardy. Watch for mites', 'Refused feeding (rare), stuck shed', 'beginner'),

('king-snake', 'California Kingsnake', 'Lampropeltis californiae', 'snake', 'Western USA, Mexico', '90-120cm', '15-20 years', '29-32°C', '26-29°C', '22-24°C', '20-22°C', '40-50%', '120x45x45cm for adult', 'Aspen, cypress', '12h cycle, UVB optional', 'Mice (kingsnakes are also ophiophagous — keep separate)', 'Juvenile: weekly. Adult: every 7-10 days', '1-1.25x body width', 'Generally tolerates handling. Strong feeding response', 'Active, food-driven. Will eat other snakes — NEVER house together', 'Hardy. Mites occasionally', 'Bite from confused feeding response, stuck shed', 'beginner'),

('milk-snake', 'Milk Snake', 'Lampropeltis triangulum', 'snake', 'North/Central America', '60-120cm (varies by subspecies)', '12-20 years', '29-32°C', '26-29°C', '22-24°C', '20-22°C', '40-50%', '90x45x45cm for adult', 'Aspen, cypress', '12h cycle', 'Mice', 'Juvenile: weekly. Adult: every 7-10 days', '1-1.25x body width', 'Active and fast. Generally tolerates handling but more flighty than corns', 'Active escape artist — secure lids essential', 'Hardy', 'Stress in poor setups, stuck shed', 'beginner'),

('western-hognose', 'Western Hognose', 'Heterodon nasicus', 'snake', 'North America (plains)', '40-90cm, females larger', '15-20 years', '29-32°C', '26-29°C', '22-24°C', '20-22°C', '30-40%', '60x45x30cm for adult', 'Aspen, sand mix, paper towel for juveniles', '12h cycle, low UVB beneficial', 'Mice. Rear-fanged but mild venom (toad-eaters)', 'Juvenile: every 5 days. Adult: every 7-10 days', '1-1.25x body width', 'Tolerates handling. May bluff strike or play dead', 'Charismatic, may hood up like cobra defensively. Rarely bites', 'Generally hardy', 'Refused feeding (common in adult males during breeding season)', 'beginner'),

('rosy-boa', 'Rosy Boa', 'Lichanura trivirgata', 'snake', 'Southwestern USA, Mexico', '60-90cm', '20-30 years', '29-32°C', '26-28°C', '20-23°C', '18-22°C', '30-40%', '90x45x30cm', 'Aspen, sand mix', '12h cycle', 'Mice', 'Juvenile: weekly. Adult: every 10-14 days', '1-1.25x body width', 'Very docile, slow-moving. Excellent for handling', 'Slow, calm. Great display species', 'Hardy. Prone to obesity if overfed', 'Obesity, mouth rot', 'beginner'),

('rainbow-boa', 'Brazilian Rainbow Boa', 'Epicrates cenchria', 'snake', 'South America', '1.2-1.8m', '20-25 years', '29-31°C', '27-29°C', '23-25°C', '22-24°C', '75-85%', '120x60x60cm for adult', 'Cypress mulch, coconut fibre — humidity holding', '12h cycle, low UVB', 'Rodents', 'Juvenile: weekly. Adult: every 10-14 days', '1-1.25x body width', 'Generally tolerates handling. Some defensive juveniles', 'Calm with age. Beautiful iridescence', 'Sensitive to humidity drops — RI risk if dry', 'Stuck shed, RI from poor husbandry', 'intermediate'),

('sand-boa', 'Kenyan Sand Boa', 'Eryx colubrinus', 'snake', 'East Africa', '40-80cm, females larger', '20-30 years', '32-35°C', '29-31°C', '23-26°C', '22-24°C', '30-40%', '60x45x20cm — burrowers, length more than height', 'Aspen, sand mix — must allow burrowing', '12h cycle', 'Mice', 'Juvenile: weekly. Adult: every 10-14 days', '1-1.25x body width', 'Generally tolerates handling. Stays under substrate most of the time', 'Hidden lifestyle. Strong feeding response', 'Hardy. Prone to obesity', 'Obesity, scale damage if substrate too sharp', 'beginner');

-- Continue with more snakes
insert into public.species (id, common_name, scientific_name, category, origin, adult_size, lifespan, temp_basking, temp_warm, temp_cool, temp_night, humidity, enclosure_size, substrate, lighting, diet, feeding_schedule, prey_size_guide, handling, temperament, health_notes, common_issues, difficulty) values
('garter-snake', 'Garter Snake', 'Thamnophis sirtalis', 'snake', 'North America', '45-130cm', '5-10 years (longer in captivity)', '29-32°C', '24-27°C', '20-22°C', '18-21°C', '50-60%', '90x45x45cm', 'Aspen, cypress', '12h cycle, UVB recommended', 'Fish (whole), earthworms, mice (some refuse)', 'Juvenile: every 4-5 days. Adult: every 7 days', 'Smaller, more frequent meals than other snakes', 'Active, tolerates handling. May musk defensively', 'Active, mildly venomous (harmless to humans). Diurnal', 'Sensitive to obesity from rodent-only diet. B1 deficiency from frozen fish', 'Refused feeding, B1 deficiency', 'beginner'),

('amazon-tree-boa', 'Amazon Tree Boa', 'Corallus hortulanus', 'snake', 'South America', '1.5-2m', '15-20 years', '29-32°C', '27-29°C', '23-25°C', '22-24°C', '75-85%', 'Arboreal: 90x60x90cm', 'Cypress, coconut fibre', '12h cycle, low UVB', 'Rodents', 'Juvenile: weekly. Adult: every 10-14 days', '1-1.25x body width', 'Minimal handling. Defensive, fast strike', 'Defensive, beautiful. Display species', 'RI from poor ventilation', 'Stuck shed, defensive bites', 'advanced'),

('false-water-cobra', 'False Water Cobra', 'Hydrodynastes gigas', 'snake', 'South America', '1.8-2.4m', '12-20 years', '29-32°C', '26-29°C', '22-24°C', '20-22°C', '50-60%', '180x60x60cm', 'Cypress, large water area', '12h cycle, UVB recommended', 'Rodents, fish, chicks', 'Juvenile: weekly. Adult: every 7-10 days', '1-1.25x body width', 'Rear-fanged venom — generally mild but caution. Active and curious', 'Active, intelligent, may hood up defensively', 'Generally hardy', 'Refused feeding rare. Defensive bites possible', 'intermediate'),

('childrens-python', 'Children''s Python', 'Antaresia childreni', 'snake', 'Northern Australia', '60-100cm', '20-30 years', '32-35°C', '28-31°C', '23-26°C', '22-24°C', '50-60%', '90x45x45cm', 'Aspen, cypress', '12h cycle, low UVB', 'Mice', 'Juvenile: weekly. Adult: every 10-14 days', '1-1.25x body width', 'Generally docile. Small and easy to handle', 'Calm, easy. Good intro to pythons', 'Hardy', 'Stuck shed', 'beginner');

-- LIZARDS / Bearded dragons, monitors
insert into public.species (id, common_name, scientific_name, category, origin, adult_size, lifespan, temp_basking, temp_warm, temp_cool, temp_night, humidity, enclosure_size, substrate, lighting, diet, feeding_schedule, prey_size_guide, handling, temperament, health_notes, common_issues, difficulty) values
('bearded-dragon', 'Bearded Dragon', 'Pogona vitticeps', 'lizard', 'Australia (arid)', '40-60cm', '10-15 years', '38-42°C basking', '30-32°C warm', '24-26°C cool', '18-21°C', '30-40%', '120x60x60cm minimum for adult', 'Tile, reptile carpet, paper. AVOID loose substrate for juveniles (impaction)', '12-14h cycle, T5 HO 10-12% UVB MANDATORY', 'Omnivore: insects (crickets, dubia) + greens (collards, mustard, squash)', 'Juvenile: 2-3x daily insects + daily greens. Adult: daily greens + insects 2-3x/week', 'Insects no larger than space between eyes', 'Tolerates handling well. Calcium + D3 supplementation essential', 'Active diurnal, charismatic. Good display species', 'MBD (metabolic bone disease) if UVB inadequate. Atadenovirus, impaction', 'MBD, impaction from loose substrate, parasites', 'beginner'),

('blue-tongue-skink', 'Blue-Tongued Skink', 'Tiliqua scincoides', 'lizard', 'Australia, Indonesia', '45-60cm', '15-20 years', '35-38°C basking', '29-31°C warm', '22-24°C cool', '18-21°C', '40-60% (subspecies varies)', '120x60x45cm for adult', 'Cypress mulch, aspen — allow burrowing', '12h cycle, 5-7% UVB recommended', 'Omnivore: 50% protein (insects, eggs, meat), 40% greens, 10% fruit', 'Juvenile: daily. Adult: every 2-3 days', 'Varied diet, mostly chopped foods', 'Tolerates handling. Slow, calm. May huff and show tongue defensively', 'Calm, intelligent. Iconic blue tongue display when stressed', 'MBD without UVB. Obesity from too much fatty food', 'Obesity, MBD, mites', 'beginner'),

('savannah-monitor', 'Savannah Monitor', 'Varanus exanthematicus', 'lizard', 'Sub-Saharan Africa', '90-130cm', '10-15 years (often less in poor conditions)', '50-60°C basking spot (large heat source)', '30-35°C warm', '24-27°C cool', '22-24°C', '60-80%', 'Large: 240x120x90cm minimum, more for adults', 'Deep substrate (50cm+) for burrowing — topsoil/sand mix', '12h cycle, T5 HO 10-12% UVB MANDATORY', 'Carnivore: insects, rodents, eggs. Whole prey preferred', 'Juvenile: daily. Adult: every 5-7 days', 'Whole prey items, insects in bulk', 'Tolerates handling if started young. Powerful tail whip, sharp claws and teeth', 'Active, intelligent, strong-willed', 'Obesity epidemic — most captive savannahs are massively overfed. Gout from high-protein dry diet', 'Obesity, gout, MBD, parasites', 'advanced'),

('ackie-monitor', 'Ackie Monitor / Spiny-Tailed Monitor', 'Varanus acanthurus', 'lizard', 'Australia (arid rocky)', '60-70cm', '15-20 years', '50-60°C basking surface (rock)', '35-40°C warm', '25-28°C cool', '22-25°C', '40-60% (humid hide)', '180x60x60cm minimum', 'Deep substrate (40cm+) — sand/topsoil for burrows', '12h cycle, T5 HO 10-12% UVB MANDATORY', 'Insects primary, occasional rodents/eggs', 'Juvenile: daily. Adult: every 2-3 days', 'Insects in bulk, supplemented', 'Tolerates handling if started young. Quick and alert', 'Active, intelligent, dwarf monitor — excellent display', 'MBD without UVB. Obesity less of an issue than savannahs', 'MBD, parasites', 'intermediate'),

('argentine-tegu', 'Argentine Black-and-White Tegu', 'Salvator merianae', 'lizard', 'South America', '90-120cm', '15-20 years', '45-55°C basking', '32-35°C warm', '24-27°C cool', '22-25°C', '60-80%', '240x120x90cm minimum for adult', 'Topsoil/cypress mix, deep for burrowing', '12-14h cycle, T5 HO 10-12% UVB MANDATORY', 'Omnivore: rodents, eggs, insects, fruit', 'Juvenile: daily. Adult: every 2-3 days', 'Whole prey, varied diet', 'Tolerates handling if socialised young. Brumates in winter', 'Intelligent, dog-like with regular interaction. Powerful bite', 'MBD without UVB. Obesity from poor diet', 'Obesity, MBD, parasites', 'intermediate'),

('green-iguana', 'Green Iguana', 'Iguana iguana', 'lizard', 'Central/South America', '1.5-2m total length', '15-20 years', '38-42°C basking', '30-32°C warm', '24-27°C cool', '22-25°C', '60-80%', 'Massive: 240x180x180cm minimum for adult (custom builds required)', 'Tile, reptile carpet — climbing branches essential', '12-14h cycle, T5 HO 12% UVB MANDATORY', 'STRICT herbivore: dark leafy greens, squash, occasional fruit. NO animal protein', 'Daily fresh greens', 'Salad-based, varied', 'Males become highly territorial in breeding season. Powerful tail whip', 'Often aggressive when sexually mature, especially males', 'MBD epidemic without proper UVB. Kidney failure from protein in diet', 'MBD, kidney disease, aggression', 'advanced'),

('chinese-water-dragon', 'Chinese Water Dragon', 'Physignathus cocincinus', 'lizard', 'Southeast Asia', '60-90cm', '10-15 years', '32-35°C basking', '28-30°C warm', '24-26°C cool', '22-25°C', '70-85%', '150x90x150cm (tall, arboreal)', 'Cypress mulch, coconut fibre. Large water area essential', '12h cycle, T5 HO 10-12% UVB MANDATORY', 'Insectivore mainly: crickets, dubia, occasional pinkies and greens', 'Juvenile: daily. Adult: every 2-3 days', 'Insects appropriate size', 'Tolerates handling. Will hit glass and damage face if cage too small', 'Active, may be skittish. Need large enclosure', 'MBD, snout damage from glass strikes, parasites', 'Snout rubs, MBD, drowning in shallow water', 'intermediate'),

('uromastyx', 'Uromastyx', 'Uromastyx species', 'lizard', 'North Africa, Middle East (arid)', '25-45cm depending on species', '15-30 years', '50-60°C basking', '38-42°C warm', '25-28°C cool', '22-25°C', '20-30% (very dry)', '120x60x45cm', 'Sand, gravel — desert setup', '12h cycle, T5 HO 12% UVB MANDATORY (high-output)', 'STRICT herbivore: seeds, lentils, dry greens. AVOID animal protein and high-water vegetables', 'Daily small amounts', 'Varied dry diet', 'Tolerates handling, may flee or use spiny tail defensively', 'Bold colours, basking lovers. Hardy in proper setup', 'Kidney issues from incorrect diet (too much protein/water). MBD without high UVB', 'MBD, kidney issues, fungal from too high humidity', 'intermediate');

-- GECKOS
insert into public.species (id, common_name, scientific_name, category, origin, adult_size, lifespan, temp_basking, temp_warm, temp_cool, temp_night, humidity, enclosure_size, substrate, lighting, diet, feeding_schedule, prey_size_guide, handling, temperament, health_notes, common_issues, difficulty) values
('leopard-gecko', 'Leopard Gecko', 'Eublepharis macularius', 'gecko', 'South Asia (Afghanistan, Pakistan, India)', '20-25cm', '15-20 years', '30-32°C warm surface (belly heat from below)', '28-30°C warm', '22-24°C cool', '20-22°C', '30-40% with humid hide', '90x45x45cm for adult', 'Tile, slate, paper towel. NO sand for juveniles', '12h cycle. Low UVB (2-5%) increasingly recommended', 'Insectivore: crickets, dubia, mealworms, occasional waxworms', 'Juvenile: daily. Adult: every 2-3 days', 'Insects no longer than space between eyes', 'Very tolerant of handling. Slow, easy', 'Calm, easy. Iconic beginner species', 'MBD without calcium/D3. Impaction from sand', 'Impaction, MBD, dropped tails from stress', 'beginner'),

('crested-gecko', 'Crested Gecko', 'Correlophus ciliatus', 'gecko', 'New Caledonia', '20-25cm including tail', '15-20 years', 'Room temp 22-26°C — NO basking spot', '22-26°C', '20-23°C', '18-22°C', '60-80%', '45x45x60cm (vertical, arboreal)', 'Coconut fibre, sphagnum, bioactive setups work well', '12h cycle, low UVB (2-5%) beneficial', 'Pangea/Repashy commercial gecko diet (CGD) + occasional insects', '3x weekly CGD. Insects 1-2x weekly for variety', 'Crickets appropriately sized', 'Tolerates handling but easily drops tail (does not regrow). Jumpy', 'Active at night. Will lose tail if grabbed', 'MBD on insect-only diets. Fall injuries', 'Tail loss, MBD if no calcium', 'beginner'),

('gargoyle-gecko', 'Gargoyle Gecko', 'Rhacodactylus auriculatus', 'gecko', 'New Caledonia', '20-25cm', '15-20 years', '22-26°C — no basking', '22-26°C', '20-23°C', '18-22°C', '50-70%', '45x45x60cm (vertical)', 'Coconut fibre, bioactive', '12h cycle, low UVB beneficial', 'CGD + insects (more carnivorous than crested)', '3x weekly CGD + insects 1-2x weekly', 'Appropriate cricket/dubia size', 'Tolerates handling. Tail regrows (unlike crested)', 'Hardy, active', 'MBD without calcium', 'MBD, fall injuries', 'beginner'),

('day-gecko', 'Madagascar Giant Day Gecko', 'Phelsuma grandis', 'gecko', 'Madagascar', '25-30cm', '10-15 years', '30-32°C basking', '27-29°C warm', '23-25°C cool', '22-24°C', '60-80%', '45x45x90cm (arboreal)', 'Coconut fibre, bioactive', '12h cycle, T5 HO 10-12% UVB MANDATORY', 'Insects + CGD/fruit nectar', 'Juvenile: daily. Adult: every 2 days', 'Appropriate insect size', 'Display species, minimal handling — fragile skin tears', 'Bold colours, diurnal, very active', 'MBD without UVB. Skin damage from handling', 'Skin tears, MBD', 'intermediate'),

('tokay-gecko', 'Tokay Gecko', 'Gekko gecko', 'gecko', 'Southeast Asia', '25-35cm', '10-15 years', '30-32°C basking', '27-29°C warm', '23-26°C cool', '22-24°C', '60-80%', '45x45x60cm minimum', 'Coconut fibre, bioactive options', '12h cycle, low UVB beneficial', 'Insects', 'Adult: every 2-3 days', 'Appropriate insect size', 'Display species. Powerful bite, will hold on. Minimal handling', 'Notoriously defensive. Loud calls', 'Hardy. Imports often parasite-laden', 'Parasites in WC animals, bite injuries to keeper', 'intermediate'),

('african-fat-tailed-gecko', 'African Fat-Tailed Gecko', 'Hemitheconyx caudicinctus', 'gecko', 'West Africa', '20-25cm', '15-20 years', '30-32°C warm', '28-30°C warm', '22-25°C cool', '20-22°C', '50-70%, humid hide essential', '60x45x30cm', 'Cypress mulch, coconut fibre', '12h cycle, low UVB optional', 'Insects', 'Juvenile: daily. Adult: every 2-3 days', 'Appropriate insect size', 'Tolerates handling. Slow and calm', 'Calm, similar to leopard gecko but more humidity', 'MBD, stuck shed from low humidity', 'Stuck shed, MBD', 'beginner'),

('mourning-gecko', 'Mourning Gecko', 'Lepidodactylus lugubris', 'gecko', 'Indo-Pacific', '8-10cm', '5-10 years', '26-28°C', '24-26°C', '22-24°C', '20-22°C', '60-80%', '30x30x45cm (small group)', 'Coconut fibre, bioactive', '12h cycle, low UVB beneficial', 'CGD + small insects (fruit flies, pinhead crickets)', '3x weekly CGD + insects', 'Tiny insects', 'Display species — too small to handle', 'Parthenogenic — all female, breed without males. Group housing works', 'Generally hardy', 'Fall injuries if escape', 'beginner');

-- TORTOISES
insert into public.species (id, common_name, scientific_name, category, origin, adult_size, lifespan, temp_basking, temp_warm, temp_cool, temp_night, humidity, enclosure_size, substrate, lighting, diet, feeding_schedule, prey_size_guide, handling, temperament, health_notes, common_issues, difficulty) values
('russian-tortoise', 'Russian Tortoise', 'Testudo horsfieldii', 'tortoise', 'Central Asia', '15-25cm', '40-50+ years', '32-38°C basking', '24-27°C warm', '20-22°C cool', '15-20°C', '40-60%', '120x60cm minimum (outdoor preferred when possible)', 'Topsoil/sand mix, hay', '12h cycle, T5 HO 10-12% UVB MANDATORY', 'STRICT herbivore: dark leafy greens, weeds (dandelion, plantain). NO fruit', 'Daily fresh greens', 'Salad-based', 'Tolerates handling but stress-prone. Outdoor time essential', 'Hardy. Brumates in cool conditions. Active diggers', 'MBD without UVB. Pyramiding from poor diet/dehydration', 'Pyramiding, MBD, RI from low temps', 'beginner'),

('sulcata-tortoise', 'Sulcata / African Spurred Tortoise', 'Centrochelys sulcata', 'tortoise', 'Sub-Saharan Africa', '60-80cm, 50-100kg+ adult', '60-100 years', '35-40°C basking', '27-30°C warm', '22-25°C cool', '18-22°C', '40-60%', 'MASSIVE: outdoor enclosure essential as adult, sheds for night/cold. NEVER suitable as indoor-only adult', 'Topsoil, sand, hay', '12-14h cycle, T5 HO 10-12% UVB MANDATORY', 'Grasses, hay, leafy greens. NO fruit, NO animal protein', 'Daily grazing — should have constant access to grass/hay', 'Grass-based diet', 'Tolerates handling but very strong. Will plow through enclosures', 'Powerful diggers. Need significant space. Cold-sensitive', 'MBD, pyramiding, stones (urinary). Cold exposure deaths', 'Pyramiding, RI from cold, escape attempts', 'advanced'),

('hermanns-tortoise', 'Hermann''s Tortoise', 'Testudo hermanni', 'tortoise', 'Southern Europe', '15-25cm', '50+ years', '32-38°C basking', '24-27°C warm', '20-22°C cool', '15-20°C', '40-60%', '120x60cm minimum, outdoor preferred', 'Topsoil/sand mix', '12h cycle, T5 HO 10-12% UVB MANDATORY', 'STRICT herbivore: weeds, dark leafy greens. NO fruit', 'Daily greens', 'Salad-based', 'Tolerates handling. Brumates', 'Hardy, similar to Russian', 'MBD, pyramiding from poor diet', 'Pyramiding, MBD, RI', 'beginner'),

('leopard-tortoise', 'Leopard Tortoise', 'Stigmochelys pardalis', 'tortoise', 'Sub-Saharan Africa', '40-50cm', '50-80 years', '32-38°C basking', '27-30°C warm', '22-26°C cool', '20-23°C', '40-60%', '180x90cm minimum, outdoor preferred', 'Topsoil/sand mix, grass', '12h cycle, T5 HO 10-12% UVB MANDATORY', 'STRICT herbivore: grass, hay, greens. NO fruit', 'Daily grass/greens', 'Grass-based', 'Tolerates handling. Does NOT brumate (cold-sensitive)', 'Hardy in warm climates. Sensitive to cold/damp', 'Pyramiding, MBD, RI from cold/damp', 'Pyramiding, RI, MBD', 'intermediate'),

('red-foot-tortoise', 'Red-Footed Tortoise', 'Chelonoidis carbonarius', 'tortoise', 'South America (tropical)', '30-40cm', '50-90 years', '30-35°C basking', '27-29°C warm', '22-25°C cool', '20-23°C', '70-85%', '180x90cm', 'Cypress mulch, topsoil — moisture-retaining', '12h cycle, T5 HO 10-12% UVB MANDATORY', 'Omnivore (unusual): greens, fruit, occasional protein (insects, mushrooms)', 'Daily, varied', 'Varied diet', 'Tolerates handling. Tropical species — no brumation', 'Calm, social. Tropical setup essential', 'Pyramiding, RI from cold', 'Pyramiding, RI, parasites', 'intermediate'),

('greek-tortoise', 'Greek Tortoise', 'Testudo graeca', 'tortoise', 'Mediterranean, North Africa', '15-30cm', '50+ years', '32-38°C basking', '24-27°C warm', '20-22°C cool', '15-20°C', '40-60%', '120x60cm minimum', 'Topsoil/sand mix', '12h cycle, T5 HO 10-12% UVB MANDATORY', 'STRICT herbivore: weeds, leafy greens', 'Daily greens', 'Salad-based', 'Tolerates handling. Brumates', 'Hardy. Similar to Hermann''s', 'MBD, pyramiding', 'Pyramiding, RI', 'beginner');

-- More common species
insert into public.species (id, common_name, scientific_name, category, origin, adult_size, lifespan, temp_basking, temp_warm, temp_cool, temp_night, humidity, enclosure_size, substrate, lighting, diet, feeding_schedule, prey_size_guide, handling, temperament, health_notes, common_issues, difficulty) values
('ball-python-genetic', 'Ball Python (Genetic Morph)', 'Python regius', 'snake', 'West/Central Africa', '1.2-1.5m', '20-30 years', '32-35°C', '29-31°C', '24-26°C', '22-25°C', '55-65%', '120x60x60cm for adult', 'Cypress, aspen', '12h cycle', 'Rodents', 'See ball-python', 'Same as ball-python', 'Same as ball-python', 'Same as ball-python', 'Some morphs (spider, super champagne) have neurological wobble', 'Wobble in spider gene combos. Same as ball-python', 'beginner'),

('rough-green-snake', 'Rough Green Snake', 'Opheodrys aestivus', 'snake', 'Southeastern USA', '60-100cm', '5-8 years', '27-30°C basking', '24-27°C warm', '20-22°C cool', '18-20°C', '50-60%', '60x45x60cm (arboreal)', 'Coconut fibre, plant-heavy', '12h cycle, UVB recommended', 'Insectivore: crickets, soft-bodied insects', 'Every 2-3 days', 'Appropriate insect size', 'Display species. Stresses easily from handling', 'Diurnal, active. Beautiful colour', 'Stress-prone. Dietary issues if not insectivore-fed', 'Refused feeding, stress', 'intermediate'),

('white-lipped-python', 'White-Lipped Python', 'Bothrochilus albertisii', 'snake', 'New Guinea', '1.8-2.4m', '15-20 years', '30-32°C', '28-30°C', '24-26°C', '22-24°C', '70-80%', '180x60x60cm', 'Cypress, sphagnum', '12h cycle, low UVB', 'Rodents', 'Adult: every 10-14 days', '1-1.25x body width', 'Defensive, fast strike. Minimal handling recommended', 'Beautiful iridescent black. Defensive', 'RI from poor ventilation', 'Defensive bites, stuck shed', 'advanced'),

('black-pine-snake', 'Black Pine Snake', 'Pituophis melanoleucus lodingi', 'snake', 'Southern USA', '1.5-2m', '15-25 years', '29-32°C', '26-29°C', '22-25°C', '20-22°C', '40-50%', '180x60x45cm', 'Aspen, cypress', '12h cycle', 'Rodents', 'Adult: every 10-14 days', '1-1.25x body width', 'May hiss loudly when threatened. Tolerates handling with time', 'Bold display, loud hiss bluff', 'Hardy', 'Stuck shed, defensive', 'intermediate'),

('bull-snake', 'Bull Snake', 'Pituophis catenifer sayi', 'snake', 'Central North America', '1.2-2.5m', '15-25 years', '29-32°C', '26-29°C', '22-25°C', '20-22°C', '40-50%', '180x60x45cm', 'Aspen, cypress', '12h cycle', 'Rodents', 'Adult: every 10-14 days', '1-1.25x body width', 'May be defensive, loud hiss. Mostly settles with time', 'Active, large North American colubrid', 'Hardy', 'Defensive juveniles, stuck shed', 'intermediate'),

('rosy-rat-snake', 'Rosy Rat Snake', 'Pantherophis guttatus guttatus', 'snake', 'Florida', '90-150cm', '15-23 years', '29-32°C', '26-29°C', '22-24°C', '20-22°C', '50-60%', '120x45x45cm', 'Aspen, cypress', '12h cycle', 'Mice', 'Adult: every 7-10 days', '1-1.25x body width', 'Active, tolerates handling', 'Similar to corn snake. Slightly more humid environment', 'Hardy', 'Stuck shed', 'beginner'),

('asian-vine-snake', 'Asian Vine Snake', 'Ahaetulla nasuta', 'snake', 'Southeast Asia', '1.5-2m', '5-10 years', '29-32°C', '27-29°C', '23-25°C', '22-24°C', '70-80%', 'Arboreal: 90x45x90cm', 'Coconut fibre, plant-heavy', '12h cycle, UVB recommended', 'Lizards primarily, some take rodents', 'Every 5-7 days', 'Appropriate size prey', 'Display only. Rear-fanged mild venom. Cannot tolerate handling', 'Beautiful, fragile. Display species', 'Stress-sensitive. Wild-caught animals high parasite load', 'Refused feeding, parasites', 'advanced'),

('mexican-black-kingsnake', 'Mexican Black Kingsnake', 'Lampropeltis getula nigrita', 'snake', 'Northern Mexico', '90-120cm', '15-20 years', '29-32°C', '26-29°C', '22-24°C', '20-22°C', '40-50%', '120x45x45cm', 'Aspen, cypress', '12h cycle', 'Mice', 'Adult: every 7-10 days', '1-1.25x body width', 'Active, generally tolerates handling. Strong feeding response', 'Beautiful all-black. Active, food-driven', 'Hardy', 'Bites from feeding response. Stuck shed', 'beginner'),

('grey-banded-kingsnake', 'Grey-Banded Kingsnake', 'Lampropeltis alterna', 'snake', 'Southwestern USA, Mexico', '60-120cm', '15-20 years', '29-32°C', '26-29°C', '22-24°C', '20-22°C', '40-50%', '90x45x45cm', 'Aspen', '12h cycle', 'Mice (sometimes lizards in wild)', 'Adult: every 7-10 days', '1-1.25x body width', 'Tolerates handling. Nocturnal/crepuscular', 'Shy, secretive. Beautiful pattern variation', 'Hardy. Some refuse rodents and need lizard-scenting', 'Refused feeding in some, stuck shed', 'intermediate'),

('eastern-indigo', 'Eastern Indigo Snake', 'Drymarchon couperi', 'snake', 'Southeastern USA (protected, CITES)', '2-2.6m', '15-25 years', '29-32°C', '26-29°C', '22-25°C', '20-23°C', '50-60%', '240x90x60cm minimum', 'Cypress, aspen', '12h cycle, UVB recommended', 'Whole prey including rodents, fish, chicks', 'Adult: every 7-10 days', 'Larger meals than typical', 'Tolerates handling well. Active', 'Active, intelligent, diurnal. Protected — papers required', 'Hardy if cared for properly', 'Stress in poor setups', 'advanced'),

('viper-boa', 'Viper Boa', 'Candoia aspera', 'snake', 'New Guinea, Solomon Islands', '60-90cm', '15-20 years', '29-32°C', '26-29°C', '22-25°C', '20-22°C', '60-70%', '90x45x30cm', 'Coconut fibre, cypress', '12h cycle, low UVB', 'Mice', 'Adult: every 10-14 days', '1-1.25x body width', 'Tolerates handling. Stocky body', 'Calm, sometimes defensive juveniles', 'Hardy', 'Stuck shed, mites in imports', 'intermediate'),

('woma-python', 'Woma Python', 'Aspidites ramsayi', 'snake', 'Central Australia', '1.5-2.5m', '20-30 years', '32-35°C', '29-31°C', '23-26°C', '22-24°C', '40-50%', '180x60x45cm', 'Aspen, cypress', '12h cycle, low UVB', 'Rodents (eats other snakes in wild)', 'Adult: every 10-14 days', '1-1.25x body width', 'Generally docile. Strong feeding response — careful at feeding', 'Calm. Eats snakes in wild — never co-habitate', 'Hardy', 'Aggressive feeding response, stuck shed', 'intermediate'),

('black-headed-python', 'Black-Headed Python', 'Aspidites melanocephalus', 'snake', 'Northern Australia', '2-2.5m', '20-30 years', '32-35°C', '29-31°C', '23-26°C', '22-24°C', '40-50%', '180x60x45cm', 'Aspen, cypress', '12h cycle', 'Rodents (snake-eater in wild)', 'Adult: every 10-14 days', '1-1.25x body width', 'Generally docile. Powerful feeding response', 'Calm. Striking black head', 'Hardy', 'Feeding response bites, stuck shed', 'intermediate'),

('jungle-carpet-python', 'Jungle Carpet Python', 'Morelia spilota cheynei', 'snake', 'Queensland Australia', '1.8-2.2m', '15-25 years', '32-35°C', '28-31°C', '23-26°C', '21-23°C', '50-60%', '180x60x60cm (arboreal)', 'Cypress, aspen', '12h cycle, low UVB', 'Rodents', 'Adult: every 10-14 days', '1-1.25x body width', 'May be defensive as juvenile, settles with age', 'Bold yellow-black pattern. Active', 'Hardy', 'Stuck shed, defensive juveniles', 'intermediate'),

('coastal-carpet-python', 'Coastal Carpet Python', 'Morelia spilota mcdowelli', 'snake', 'Eastern Australia', '2-3m', '15-25 years', '32-35°C', '28-31°C', '23-26°C', '21-23°C', '50-60%', '210x60x60cm', 'Cypress', '12h cycle', 'Rodents', 'Adult: every 10-14 days', '1-1.25x body width', 'Generally tolerates handling', 'Largest of carpet pythons. Calm with handling', 'Hardy', 'Stuck shed', 'intermediate'),

('jamaican-boa', 'Jamaican Boa', 'Chilabothrus subflavus', 'snake', 'Jamaica (CITES)', '1.5-2m', '20-30 years', '29-32°C', '27-29°C', '23-25°C', '22-24°C', '70-80%', '150x60x60cm', 'Cypress, sphagnum', '12h cycle, low UVB', 'Rodents, birds', 'Adult: every 10-14 days', '1-1.25x body width', 'Generally tolerates handling', 'Iridescent, beautiful. CITES — papers required', 'Sensitive to husbandry', 'Stuck shed, RI', 'intermediate'),

('garden-tree-boa', 'Garden Tree Boa', 'Corallus hortulanus', 'snake', 'South America', '1.5-2m', '15-20 years', '29-32°C', '27-29°C', '23-25°C', '22-24°C', '70-85%', 'Arboreal: 90x60x90cm', 'Cypress, sphagnum', '12h cycle, low UVB', 'Rodents', 'Adult: every 10-14 days', '1-1.25x body width', 'Defensive. Display species', 'Highly variable colours. Defensive', 'RI risk', 'Defensive bites, stuck shed', 'advanced');

-- More lizards and geckos
insert into public.species (id, common_name, scientific_name, category, origin, adult_size, lifespan, temp_basking, temp_warm, temp_cool, temp_night, humidity, enclosure_size, substrate, lighting, diet, feeding_schedule, prey_size_guide, handling, temperament, health_notes, common_issues, difficulty) values
('red-ackie', 'Red Ackie Monitor', 'Varanus acanthurus brachyurus', 'lizard', 'Australia', '60-70cm', '15-20 years', '50-60°C basking surface', '35-40°C warm', '25-28°C cool', '22-25°C', '40-60% with humid hide', '180x60x60cm', 'Deep substrate (40cm+) sand/topsoil', '12h cycle, T5 HO 10-12% UVB', 'Insects, occasional rodents/eggs', 'Adult: every 2-3 days', 'Insects in bulk', 'Tolerates handling if socialised young', 'Active dwarf monitor. Red coloration', 'MBD without UVB', 'MBD, parasites', 'intermediate'),

('crocodile-skink', 'Crocodile Skink', 'Tribolonotus gracilis', 'lizard', 'New Guinea', '15-22cm', '5-10 years', '26-28°C basking', '24-26°C warm', '22-24°C cool', '21-23°C', '70-90%', '60x45x30cm', 'Coconut fibre, sphagnum. Water area essential', '12h cycle, low UVB', 'Insects', 'Every 2-3 days', 'Small insects', 'Display species. Stress-prone — minimal handling', 'Shy, hides often. Vocal (squeaks)', 'Stress-sensitive', 'Stress, refused feeding', 'intermediate'),

('chinese-cave-gecko', 'Chinese Cave Gecko', 'Goniurosaurus hainanensis', 'gecko', 'Southern China, Vietnam', '15-18cm', '10-12 years', '24-26°C — NO basking spot', '22-24°C', '20-22°C', '18-20°C', '70-80%', '45x30x30cm', 'Coconut fibre, sphagnum', '12h cycle, low UVB', 'Insects', 'Every 2-3 days', 'Small insects', 'Cool, humid setup. Minimal handling', 'Nocturnal, shy', 'Heat-sensitive (overheating kills)', 'Overheating, stress', 'advanced'),

('viper-gecko', 'Viper Gecko', 'Hemidactylus imbricatus', 'gecko', 'Pakistan', '8-10cm', '5-8 years', '32-35°C basking', '28-30°C warm', '23-26°C cool', '20-23°C', '40-50%', '45x30x30cm', 'Sand, slate', '12h cycle', 'Small insects', 'Every 2-3 days', 'Pinhead crickets, fruit flies', 'Tiny, display only', 'Active, communal', 'Hardy', 'Refused feeding if temps wrong', 'beginner'),

('helmeted-gecko', 'Helmeted Gecko', 'Tarentola chazaliae', 'gecko', 'Northwest Africa', '10-12cm', '8-10 years', '32-35°C basking', '28-30°C warm', '23-26°C cool', '20-22°C', '40-50%', '60x30x30cm', 'Sand, rock', '12h cycle, low UVB', 'Insects', 'Every 2-3 days', 'Small crickets, dubia', 'Tolerates light handling', 'Hardy, calm', 'Generally hardy', 'Refused feeding rare', 'beginner'),

('panther-chameleon', 'Panther Chameleon', 'Furcifer pardalis', 'lizard', 'Madagascar', '40-50cm males, 25-30cm females', '5-7 years', '32-35°C basking', '26-29°C warm', '22-24°C cool', '20-22°C', '60-80%, drip systems essential', '60x60x120cm (vertical, mesh)', 'Bioactive optional, paper/no substrate works', '12h cycle, T5 HO 6-7% UVB MANDATORY', 'Insects (crickets, dubia, hornworms)', 'Juvenile: daily. Adult: every 2-3 days', 'Appropriate insect size, varied', 'Display only — handling = stress', 'Solitary, territorial. Stress easily', 'MBD, kidney issues from dehydration. Generally short-lived in captivity', 'MBD, dehydration, eye issues', 'advanced'),

('veiled-chameleon', 'Veiled Chameleon', 'Chamaeleo calyptratus', 'lizard', 'Yemen, Saudi Arabia', '35-50cm', '5-8 years', '32-35°C basking', '26-29°C warm', '22-24°C cool', '20-22°C', '50-70% with drip system', '60x60x120cm (vertical, mesh)', 'Paper/no substrate', '12h cycle, T5 HO 6-7% UVB MANDATORY', 'Insects + occasional greens', 'Juvenile: daily. Adult: every 2-3 days', 'Appropriate insect size', 'Display only', 'Solitary, sometimes aggressive', 'MBD, kidney issues, eye issues from low humidity', 'MBD, dehydration', 'intermediate'),

('jacksons-chameleon', 'Jackson''s Chameleon', 'Trioceros jacksonii', 'lizard', 'East Africa highlands', '25-35cm', '5-8 years', '26-28°C basking (cooler than other chams)', '22-25°C warm', '18-22°C cool', '15-20°C night drop required', '60-70%', '60x60x120cm', 'Paper/none', '12h cycle, T5 HO 5-7% UVB MANDATORY', 'Insects', 'Adult: every 2-3 days', 'Appropriate insect size', 'Display only', 'Live-bearing. Cool temps essential — overheating kills', 'Heat-sensitive, MBD', 'Overheating, MBD', 'advanced'),

('frilled-lizard', 'Frilled Lizard', 'Chlamydosaurus kingii', 'lizard', 'Northern Australia, New Guinea', '60-90cm with tail', '10-15 years', '38-42°C basking', '30-32°C warm', '24-27°C cool', '22-24°C', '50-70%', '120x60x150cm (tall, arboreal)', 'Cypress, sand mix', '12h cycle, T5 HO 10-12% UVB', 'Insects + occasional rodents', 'Juvenile: daily. Adult: every 2-3 days', 'Appropriate prey size', 'Tolerates handling. May display frill defensively', 'Iconic display. Generally calm', 'MBD without proper UVB', 'MBD', 'intermediate'),

('argus-monitor', 'Argus Monitor', 'Varanus panoptes', 'lizard', 'Northern Australia, New Guinea', '1-1.4m', '15-20 years', '50-60°C basking surface', '32-37°C warm', '24-27°C cool', '22-25°C', '50-70%', '240x120x90cm minimum', 'Deep substrate (50cm+) topsoil/sand', '12h cycle, T5 HO 10-12% UVB', 'Insects, rodents, eggs', 'Adult: every 3-5 days', 'Whole prey', 'Active, intelligent. Tolerates handling if socialised', 'Active diurnal, dog-like', 'MBD, obesity if overfed', 'Obesity, MBD', 'advanced'),

('asian-water-monitor', 'Asian Water Monitor', 'Varanus salvator', 'lizard', 'South/Southeast Asia', '1.5-2m (some over 2.5m)', '15-20 years', '40-50°C basking', '30-35°C warm', '24-27°C cool', '22-25°C', '70-80%', '300x150x150cm minimum, large water area', 'Soil, with significant water', '12h cycle, T5 HO 10-12% UVB', 'Carnivore: rodents, fish, chicks', 'Adult: every 5-7 days', 'Whole prey', 'Powerful, requires experienced handler', 'Intelligent, can be aggressive. Powerful tail, bite, and claws', 'MBD, parasites', 'Aggression, MBD', 'expert'),

('chinese-crocodile-lizard', 'Chinese Crocodile Lizard', 'Shinisaurus crocodilurus', 'lizard', 'Southern China, Vietnam (CITES)', '20-40cm', '10-15 years', '26-28°C basking', '22-24°C warm', '18-22°C cool', '15-18°C', '70-90%', '90x45x45cm with water area', 'Cypress, sphagnum, lots of water', '12h cycle, low UVB', 'Insects, small fish, occasional pinkies', 'Every 2-3 days', 'Varied small prey', 'Display only, CITES paperwork required', 'Semi-aquatic, calm', 'Cold-sensitive but heat-sensitive too', 'Stress, RI', 'advanced'),

('caiman-lizard', 'Caiman Lizard', 'Dracaena guianensis', 'lizard', 'South America', '90-120cm', '10-15 years', '32-35°C basking', '28-30°C warm', '24-26°C cool', '22-24°C', '70-85%', '240x120x120cm with large water area', 'Cypress, sand. Large pool essential', '12h cycle, T5 HO 10-12% UVB', 'Snails primarily, fish, shrimp', 'Adult: every 2-3 days', 'Whole snails, fish', 'Powerful jaws. Tolerates limited handling', 'Semi-aquatic, snail-cruncher', 'Calcium-rich diet essential', 'MBD without proper diet', 'advanced'),

('green-anole', 'Green Anole', 'Anolis carolinensis', 'lizard', 'Southeastern USA', '15-20cm', '5-8 years', '30-32°C basking', '26-28°C warm', '22-24°C cool', '20-22°C', '60-70%, mist daily', '45x45x60cm (vertical)', 'Coconut fibre, plant-heavy', '12h cycle, T5 HO 5-7% UVB MANDATORY', 'Small insects', 'Every 1-2 days', 'Small crickets, fruit flies', 'Display only — stress easily, tail drops', 'Diurnal, colour-changing', 'MBD without UVB. Dehydration', 'MBD, stress', 'beginner'),

('cuban-knight-anole', 'Cuban Knight Anole', 'Anolis equestris', 'lizard', 'Cuba', '30-50cm', '8-12 years', '32-35°C basking', '27-30°C warm', '24-26°C cool', '22-24°C', '60-80%', '90x60x90cm', 'Coconut fibre, plants', '12h cycle, T5 HO 6-7% UVB', 'Insects, occasional pinkies', 'Adult: every 2-3 days', 'Larger crickets, dubia', 'Display, may bite when handled', 'Active, large anole. Defensive', 'MBD without UVB', 'MBD, bites', 'intermediate'),

('schneiders-skink', 'Schneider''s Skink', 'Eumeces schneideri', 'lizard', 'Middle East, North Africa', '30-45cm', '15-20 years', '40-45°C basking', '30-32°C warm', '24-26°C cool', '20-22°C', '30-40%', '120x60x45cm', 'Sand, soil — burrowing', '12h cycle, T5 HO 10-12% UVB', 'Insects + greens + occasional pinkies', 'Adult: every 2-3 days', 'Varied diet', 'Tolerates handling with time', 'Active diurnal, hardy', 'MBD without UVB', 'MBD', 'intermediate'),

('blue-tongue-northern', 'Northern Blue-Tongued Skink', 'Tiliqua scincoides intermedia', 'lizard', 'Northern Australia', '50-60cm', '15-25 years', '35-38°C basking', '29-31°C warm', '22-24°C cool', '18-21°C', '40-60%', '120x60x45cm', 'Cypress mulch, aspen', '12h cycle, 5-7% UVB recommended', 'Omnivore: 50% protein, 40% greens, 10% fruit', 'Adult: every 2-3 days', 'Varied chopped diet', 'Tolerates handling well', 'Calm, slightly larger than common BTS', 'MBD, obesity', 'Obesity, MBD', 'beginner'),

('eastern-blue-tongue', 'Eastern Blue-Tongued Skink', 'Tiliqua scincoides scincoides', 'lizard', 'Eastern Australia', '45-55cm', '15-25 years', '35-38°C basking', '29-31°C warm', '22-24°C cool', '18-21°C', '40-60%', '120x60x45cm', 'Cypress mulch, aspen', '12h cycle, 5-7% UVB', 'Omnivore', 'Adult: every 2-3 days', 'Varied diet', 'Tolerates handling', 'Calm, hardy', 'MBD, obesity', 'Obesity', 'beginner'),

('shingleback-skink', 'Shingleback Skink', 'Tiliqua rugosa', 'lizard', 'Southern Australia', '30-40cm', '20-50 years', '35-38°C basking', '27-30°C warm', '20-23°C cool', '15-20°C', '30-40%', '120x60x45cm', 'Sand, gravel', '12h cycle, 5-7% UVB', 'Omnivore, more vegetation than BTS', 'Adult: every 3-5 days', 'Varied diet', 'Tolerates handling, slow', 'Slow, calm, monogamous pairs in wild', 'Hardy', 'Obesity', 'intermediate'),

('greater-amphibian', 'Greater Siren', 'Siren lacertina', 'other', 'Southeastern USA', '50-100cm', '10-25 years', 'N/A aquatic', '22-26°C water', '20-22°C water', '20-22°C', 'N/A aquatic', '380L+ aquarium', 'Aquatic — bare bottom or sand', '12h cycle, low light', 'Worms, fish, invertebrates', 'Every 2-3 days', 'Varied small prey', 'Aquatic salamander, no handling', 'Nocturnal, secretive', 'Sensitive to water quality', 'Poor water quality issues', 'intermediate');

-- ============================================
-- LINK snakes table to species
-- ============================================
alter table public.snakes add column if not exists species_id text references public.species(id) on delete set null;
create index if not exists idx_snakes_species_id on public.snakes(species_id);
