-- ============================================
-- Repti-Track v0.4 — Species Library Expansion
-- Adds ~100 more pet trade species + SA natives
-- Run AFTER species_data.sql
-- ============================================

insert into public.species (id, common_name, scientific_name, category, origin, adult_size, lifespan, temp_basking, temp_warm, temp_cool, temp_night, humidity, enclosure_size, substrate, lighting, diet, feeding_schedule, prey_size_guide, handling, temperament, health_notes, common_issues, difficulty) values

-- ============================================
-- ADDITIONAL SNAKES (Colubrids & rare pythons)
-- ============================================
('rainbow-boa-colombian', 'Colombian Rainbow Boa', 'Epicrates maurus', 'snake', 'Colombia, Venezuela, Trinidad', '1.2-1.8m', '15-20 years', '30-32°C', '27-29°C', '24-26°C', '22-24°C', '70-85%', '120x60x60cm minimum for adult', 'Cypress mulch, sphagnum moss for humidity', '12h cycle, low UVB optional', 'Mice and small rats', 'Juvenile: weekly. Adult: every 10-14 days', 'Prey 1-1.25x body width', 'Tolerates handling, can be nippy as juveniles', 'Generally calm, less iridescent than Brazilian cousin but easier care', 'Respiratory infections from dry/cold conditions', 'Stuck sheds, mites', 'intermediate'),

('rosy-boa-mexican', 'Mexican Rosy Boa', 'Lichanura trivirgata', 'snake', 'Northern Mexico, Baja California', '60-90cm', '20-30 years', '29-32°C', '26-28°C', '21-24°C', '18-22°C', '30-40%', '90x45x45cm', 'Aspen shavings, sand mix', '12h cycle, no UVB needed', 'Small mice', 'Adult: every 10-14 days', 'Prey ~body width', 'Excellent for handling, very docile', 'Slow-moving, calm temperament', 'Obesity if overfed, scale rot if too humid', 'Refused feeding during brumation', 'beginner'),

('dumerils-boa', 'Dumeril''s Boa', 'Acrantophis dumerili', 'snake', 'Madagascar', '1.5-2m', '20-30 years', '30-32°C', '27-30°C', '23-26°C', '22-24°C', '60-70%', '150x60x60cm for adult', 'Cypress, aspen, coconut fibre', '12h cycle, low UVB optional', 'Mice and rats', 'Juvenile: weekly. Adult: every 14 days', 'Prey 1-1.25x body width', 'Tolerates handling well, heavy-bodied', 'Generally docile, slow-moving', 'Respiratory infections, internal parasites', 'Refused feeding, stuck sheds', 'intermediate'),

('madagascar-tree-boa', 'Madagascar Tree Boa', 'Sanzinia madagascariensis', 'snake', 'Madagascar', '1.2-1.8m', '20-25 years', '28-30°C', '26-28°C', '22-24°C', '20-22°C', '70-80%', 'Tall: 90x60x120cm with branches', 'Cypress mulch, sphagnum moss', '12h cycle, low UVB beneficial', 'Mice and small rats', 'Every 10-14 days', 'Prey ~body width', 'Can be defensive, handle carefully', 'Arboreal, nervous as juveniles, calmer with age', 'Respiratory infections, mites', 'Stuck sheds from low humidity', 'intermediate'),

('hognose-eastern', 'Eastern Hognose Snake', 'Heterodon platirhinos', 'snake', 'Eastern North America', '50-90cm', '10-15 years', '30-32°C', '27-29°C', '22-25°C', '20-23°C', '30-50%', '90x45x45cm', 'Aspen, cypress, sand mix', '12h cycle, low UVB optional', 'Rodents (often refuse, may need toad-scenting)', 'Every 7-10 days', 'Small mice', 'Mildly venomous (rear-fanged, harmless to most humans), generally calm', 'Famous for playing dead and bluffing strikes', 'Refused feeding (very common)', 'Refused food is the #1 issue', 'intermediate'),

('puff-adder', 'Puff Adder', 'Bitis arietans', 'snake', 'Sub-Saharan Africa, South Africa native', '90-120cm', '15-20 years', '30-32°C', '27-29°C', '22-25°C', '18-22°C', '40-60%', '120x60x45cm', 'Sand mix, aspen', '12h cycle, low UVB optional', 'Mice and rats', 'Every 10-14 days', 'Prey ~body width', 'VENOMOUS — experts only, never handle directly', 'Slow but deadly, hot snake, requires permits in SA', 'Mites, respiratory infections', 'Stuck sheds, regurgitation', 'expert'),

('cape-cobra', 'Cape Cobra', 'Naja nivea', 'snake', 'Southern Africa, SA native', '1.2-1.6m', '15-20 years', '30-32°C', '27-29°C', '23-26°C', '20-23°C', '50-60%', '150x60x60cm minimum', 'Sand, aspen, paper', '12h cycle, low UVB optional', 'Rodents, occasional birds', 'Every 10-14 days', 'Prey 1-1.25x body width', 'HIGHLY VENOMOUS — experts only, permits required in SA', 'Alert, fast, defensive, hot snake', 'Mites, RI, stress-related issues', 'Requires expert-level husbandry', 'expert'),

('mole-snake', 'Mole Snake', 'Pseudaspis cana', 'snake', 'Southern Africa, SA native', '1.5-2m', '15-20 years', '30-32°C', '27-29°C', '22-25°C', '18-22°C', '40-50%', '120x60x60cm', 'Aspen, sand mix, cypress', '12h cycle, low UVB optional', 'Rodents, eggs', 'Every 10-14 days', 'Prey ~body width', 'Can be defensive when adult, generally calm with regular handling', 'Powerful constrictor, alert', 'Mites, occasional respiratory issues', 'Refused feeding, stuck sheds', 'intermediate'),

('brown-house-snake', 'Brown House Snake', 'Boaedon capensis', 'snake', 'Southern Africa, SA native', '60-110cm', '10-15 years', '30-32°C', '26-29°C', '22-25°C', '20-23°C', '40-50%', '90x45x45cm', 'Aspen, cypress mulch', '12h cycle, no UVB needed', 'Mice', 'Every 7-10 days', 'Prey ~body width', 'Generally docile, good handler, excellent SA beginner snake', 'Nocturnal, easy-going temperament', 'Mites, occasional refusal', 'Stuck sheds, scale rot if too wet', 'beginner'),

('rinkhals', 'Rinkhals', 'Hemachatus haemachatus', 'snake', 'Southern Africa, SA native', '90-150cm', '15-20 years', '28-30°C', '25-28°C', '20-23°C', '18-21°C', '50-60%', '120x60x45cm', 'Aspen, paper', '12h cycle, low UVB optional', 'Rodents, frogs, eggs', 'Every 10-14 days', 'Prey ~body width', 'HIGHLY VENOMOUS spitting cobra — experts only, permits required', 'Defensive, can spit venom up to 2.5m', 'Mites, RI', 'Stuck sheds, refused feeding', 'expert'),

('boomslang', 'Boomslang', 'Dispholidus typus', 'snake', 'Sub-Saharan Africa, SA native', '1.2-1.8m', '8-12 years', '28-30°C', '25-28°C', '22-25°C', '20-23°C', '60-70%', 'Tall arboreal 60x60x120cm', 'Cypress, branches essential', '12h cycle, UVB beneficial', 'Lizards, birds, eggs', 'Every 7-10 days', 'Small prey', 'HIGHLY VENOMOUS rear-fanged — experts only, permits required', 'Arboreal, generally shy but venom is lethal', 'Stress, refused feeding', 'Sensitive to husbandry errors', 'expert'),

('puff-adder-snouted-night-adder', 'Snouted Night Adder', 'Causus defilippii', 'snake', 'Eastern/Southern Africa, SA native', '40-60cm', '10-15 years', '28-30°C', '24-27°C', '20-23°C', '18-21°C', '60-70%', '60x45x45cm', 'Cypress, leaf litter', '12h cycle, low UVB optional', 'Frogs, toads (occasionally rodents)', 'Every 7-10 days', 'Small prey', 'MILDLY VENOMOUS — experts only', 'Nocturnal, generally calm but defensive when threatened', 'Refused feeding (frog-eater)', 'Stuck sheds, RI', 'expert'),

('spotted-bush-snake', 'Spotted Bush Snake', 'Philothamnus semivariegatus', 'snake', 'Sub-Saharan Africa, SA native', '80-130cm', '8-12 years', '28-30°C', '25-27°C', '22-24°C', '20-22°C', '60-75%', 'Tall arboreal 60x60x90cm', 'Coco fibre, leaf litter', '12h cycle, UVB beneficial', 'Geckos, frogs, small lizards', 'Every 5-7 days', 'Small prey', 'Non-venomous, can be flighty, handle carefully', 'Diurnal, arboreal, alert', 'Stress, refused feeding (specialist diet)', 'Difficult to feed in captivity', 'advanced'),

('rat-snake-baird', 'Baird''s Rat Snake', 'Pantherophis bairdi', 'snake', 'Texas, Mexico', '90-150cm', '15-20 years', '29-31°C', '25-28°C', '21-24°C', '20-22°C', '40-50%', '120x45x45cm', 'Aspen, cypress', '12h cycle, low UVB optional', 'Mice and small rats', 'Every 7-10 days', 'Prey ~body width', 'Calm, good handler, less common than corn snake', 'Docile, similar to corn snake care', 'Mites, RI', 'Stuck sheds, refused feeding', 'beginner'),

('rat-snake-trans-pecos', 'Trans-Pecos Rat Snake', 'Bogertophis subocularis', 'snake', 'Texas, New Mexico, Northern Mexico', '90-150cm', '15-20 years', '29-32°C', '25-28°C', '21-23°C', '18-21°C', '30-50%', '120x45x45cm', 'Aspen, sand mix', '12h cycle, low UVB optional', 'Mice', 'Every 7-10 days', 'Prey ~body width', 'Calm once acclimated, can be defensive as juvenile', 'Nocturnal, slim build', 'Mites, RI', 'Stuck sheds, refusal during winter', 'intermediate'),

('king-snake-speckled', 'Speckled Kingsnake', 'Lampropeltis holbrooki', 'snake', 'Central USA', '90-150cm', '15-20 years', '29-31°C', '25-28°C', '21-24°C', '20-22°C', '40-50%', '120x45x45cm', 'Aspen, cypress', '12h cycle, low UVB optional', 'Mice', 'Every 7-10 days', 'Prey ~body width', 'Hardy, can be food-aggressive', 'Active, alert', 'Mites, RI', 'Cannibalism — keep separately', 'beginner'),

('king-snake-florida', 'Florida Kingsnake', 'Lampropeltis getula floridana', 'snake', 'Florida, USA', '120-180cm', '15-20 years', '29-31°C', '25-28°C', '22-25°C', '20-23°C', '50-60%', '120x60x45cm', 'Cypress, aspen', '12h cycle, low UVB optional', 'Mice, small rats', 'Every 7-10 days', 'Prey ~body width', 'Hardy and active, food-aggressive', 'Active, alert', 'Mites, RI', 'Keep separate (cannibal)', 'beginner'),

('garter-checkered', 'Checkered Garter Snake', 'Thamnophis marcianus', 'snake', 'Southern USA, Mexico', '40-80cm', '8-12 years', '28-30°C', '24-27°C', '20-23°C', '18-21°C', '50-60%', '90x45x45cm', 'Aspen, cypress, with water bowl', '12h cycle, low UVB optional', 'Fish, earthworms, occasional pinkies', 'Every 5-7 days', 'Small prey items', 'Small, active, can be nippy', 'Diurnal, lively', 'Internal parasites (from fish)', 'Vitamin B1 deficiency from raw fish', 'beginner'),

('reticulated-python-dwarf', 'Dwarf Reticulated Python', 'Malayopython reticulatus (Kalatoa/Selayar)', 'snake', 'Indonesia', '2-3m', '20-25 years', '32-34°C', '28-31°C', '24-26°C', '22-24°C', '60-70%', '180x90x60cm minimum', 'Cypress, newspaper', '12h cycle, low UVB optional', 'Rats, small rabbits', 'Every 10-14 days', 'Prey 1-1.25x body width', 'Smaller than mainland retics but still powerful, two-person rule', 'Alert, can be defensive', 'Mites, RI, IBD', 'Aggression with size', 'advanced'),

('rainbow-boa-brazilian-dwarf', 'Cropan''s Boa', 'Corallus cropanii', 'snake', 'Brazil (very rare in captivity)', '1.2-1.5m', '15-20 years', '28-30°C', '26-28°C', '22-24°C', '20-22°C', '70-80%', '120x60x90cm tall', 'Coco fibre, branches', '12h cycle, low UVB beneficial', 'Mice, rats', 'Every 10-14 days', 'Prey ~body width', 'CITES protected, very rare', 'Arboreal, nervous', 'Sensitive husbandry needs', 'Refused feeding common', 'expert'),

('milk-snake-pueblan', 'Pueblan Milk Snake', 'Lampropeltis triangulum campbelli', 'snake', 'Mexico (Puebla)', '70-100cm', '15-20 years', '29-31°C', '25-28°C', '21-24°C', '20-23°C', '40-50%', '90x45x45cm', 'Aspen, cypress', '12h cycle, low UVB optional', 'Mice', 'Every 7-10 days', 'Prey ~body width', 'Generally docile, classic tri-color', 'Calm, hardy', 'Mites, RI', 'Stuck sheds', 'beginner'),

('milk-snake-honduran', 'Honduran Milk Snake', 'Lampropeltis triangulum hondurensis', 'snake', 'Honduras, Nicaragua', '120-150cm', '15-20 years', '29-31°C', '25-28°C', '21-24°C', '20-23°C', '50-60%', '120x45x45cm', 'Aspen, cypress', '12h cycle, low UVB optional', 'Mice, small rats', 'Every 7-10 days', 'Prey ~body width', 'Larger milk snake, can be food-aggressive', 'Active, hardy', 'Mites, RI', 'Cannibalism — separate housing', 'beginner'),

('python-spotted', 'Spotted Python', 'Antaresia maculosa', 'snake', 'Australia', '90-130cm', '20-25 years', '32-34°C', '28-30°C', '24-26°C', '22-24°C', '40-60%', '90x45x45cm', 'Aspen, cypress', '12h cycle, low UVB optional', 'Mice', 'Every 7-10 days', 'Prey ~body width', 'Small Aussie python, good handler, hardy', 'Calm, easy keeper', 'Mites, RI', 'Stuck sheds', 'beginner'),

('python-anthill', 'Anthill Python', 'Antaresia perthensis', 'snake', 'Western Australia', '50-70cm', '20+ years', '32-34°C', '28-30°C', '24-26°C', '22-24°C', '40-50%', '60x45x45cm', 'Aspen, sand mix', '12h cycle, low UVB optional', 'Pinky/fuzzy mice', 'Every 7-10 days', 'Small prey', 'Smallest python in the world, calm', 'Tiny but feisty as juvenile', 'Mites, RI', 'Stuck sheds, mite from dry conditions', 'intermediate'),

('python-stimsons', 'Stimson''s Python', 'Antaresia stimsoni', 'snake', 'Australia', '70-110cm', '20+ years', '32-34°C', '28-30°C', '24-26°C', '22-24°C', '40-50%', '90x45x45cm', 'Aspen, cypress', '12h cycle, low UVB optional', 'Mice', 'Every 7-10 days', 'Prey ~body width', 'Small, manageable, good Aussie alternative', 'Calm with regular handling', 'Mites, RI', 'Stuck sheds', 'beginner'),

('boa-rainbow-peruvian', 'Peruvian Rainbow Boa', 'Epicrates cenchria gaigeae', 'snake', 'Peru', '1.2-1.5m', '15-20 years', '30-32°C', '27-29°C', '24-26°C', '22-24°C', '70-80%', '120x60x60cm', 'Cypress, sphagnum', '12h cycle, low UVB optional', 'Mice and rats', 'Every 10-14 days', 'Prey ~body width', 'Beautiful iridescence, sensitive to dry conditions', 'Generally calm', 'RI from low humidity', 'Stuck sheds, scale rot', 'intermediate'),

-- ============================================
-- BALL PYTHON DESIGNER MORPHS (popular ones — kept as "varieties" for the library)
-- ============================================
-- Note: Most users will pick "Ball Python" species and write the morph in the Morph field.
-- These are only for reference if you specifically import them.

-- ============================================
-- ADDITIONAL LIZARDS
-- ============================================
('chameleon-flap-necked', 'Flap-Necked Chameleon', 'Chamaeleo dilepis', 'lizard', 'Sub-Saharan Africa, SA native', '20-35cm', '5-8 years', '28-32°C', '24-28°C', '20-23°C', '18-21°C', '50-70%', 'Tall mesh 45x45x90cm', 'Bioactive or paper towels, with live plants', '12h cycle, UVB 5-6% essential', 'Live insects: crickets, locusts, dubia', 'Daily as juvenile, every 2-3 days adult', 'Insect 1/2 head width', 'Avoid handling, stresses easily', 'Slow-moving, prehensile tail, territorial', 'MBD without UVB, dehydration, parasites', 'Stress, refused feeding, eye problems', 'advanced'),

('chameleon-cape-dwarf', 'Cape Dwarf Chameleon', 'Bradypodion pumilum', 'lizard', 'Western Cape, SA native', '10-15cm', '5-8 years', '24-28°C', '20-24°C', '16-20°C', '14-18°C', '60-80%', 'Tall mesh 30x30x60cm', 'Bioactive substrate, live plants', '12h cycle, UVB 5-6% essential', 'Small live insects', 'Daily juvenile, every 2 days adult', 'Tiny insects', 'Do not handle, sensitive', 'Slow, calm, prefers cool temperatures', 'MBD, dehydration, RI', 'Stress in heat, refused feeding', 'advanced'),

('chameleon-meller', 'Meller''s Chameleon', 'Trioceros melleri', 'lizard', 'East Africa', '60-90cm', '12-15 years', '30-32°C', '26-29°C', '22-25°C', '20-23°C', '60-70%', 'Tall mesh 90x90x180cm', 'Bioactive, large plants, branches', '12h cycle, UVB 6-10% essential', 'Large insects, small vertebrates', 'Every 2-3 days', 'Large insects', 'Avoid handling, very large chameleon', 'One of largest chameleons, slow, calm', 'MBD, RI, dehydration', 'Stress, complex husbandry', 'expert'),

('chameleon-fischer', 'Fischer''s Chameleon', 'Kinyongia fischeri', 'lizard', 'Tanzania', '35-45cm', '5-8 years', '26-30°C', '22-26°C', '18-22°C', '16-20°C', '60-80%', 'Tall mesh 60x60x120cm', 'Bioactive, branches', '12h cycle, UVB 5-6% essential', 'Crickets, roaches, hornworms', 'Daily juvenile, every 2-3 days adult', 'Insect 1/2 head width', 'Avoid handling, stresses easily', 'Two-horned, calmer than veiled', 'MBD, dehydration, eye issues', 'Stress, refused feeding', 'advanced'),

('agama-rock', 'Southern Rock Agama', 'Agama atra', 'lizard', 'Southern Africa, SA native', '15-25cm', '8-10 years', '38-42°C basking', '28-32°C', '24-26°C', '20-23°C', '30-50%', '90x45x45cm', 'Sand, rock features essential', '12h cycle, UVB 10-12% required', 'Crickets, locusts, dubia, plants', 'Daily juvenile, every other day adult', 'Insect 1/2 head width', 'Can tolerate handling with patience', 'Diurnal, sun-loving, territorial males', 'MBD, dehydration', 'Stress, refused feeding', 'intermediate'),

('agama-painted', 'Painted Agama', 'Stellagama stellio', 'lizard', 'Middle East, Greece', '25-35cm', '8-12 years', '38-42°C', '28-32°C', '24-26°C', '20-23°C', '30-50%', '120x45x45cm', 'Sand, rocks', '12h cycle, UVB 10-12% required', 'Insects + small amount of plants', 'Daily juvenile, every other day adult', 'Insect 1/2 head width', 'Skittish but tames with patience', 'Active, alert, sun-baskers', 'MBD without UVB', 'Stress, refused feeding', 'intermediate'),

('agama-tree', 'Common Tree Agama', 'Acanthocercus atricollis', 'lizard', 'Sub-Saharan Africa, SA native', '25-35cm', '6-10 years', '36-40°C', '28-32°C', '24-26°C', '20-23°C', '40-60%', 'Tall 60x60x120cm with branches', 'Coco fibre, branches essential', '12h cycle, UVB 10-12% required', 'Insects + occasional fruit', 'Daily juvenile, every 2 days adult', 'Insect 1/2 head width', 'Avoid handling — flighty', 'Arboreal, territorial males', 'MBD, dehydration', 'Stress, refused feeding', 'intermediate'),

('lizard-armadillo-girdled', 'Armadillo Girdled Lizard', 'Ouroborus cataphractus', 'lizard', 'Western South Africa, SA native', '15-20cm', '12-25 years', '32-36°C', '25-28°C', '20-23°C', '18-21°C', '30-40%', '90x45x45cm', 'Sand, slate stacks', '12h cycle, UVB 10-12% required', 'Insects: crickets, locusts, termites', 'Every 2-3 days', 'Insect 1/2 head width', 'Avoid handling, sensitive', 'Social, lives in groups, very slow-moving', 'MBD, dehydration, parasites', 'Refused feeding', 'advanced'),

('lizard-collared', 'Eastern Collared Lizard', 'Crotaphytus collaris', 'lizard', 'Central USA', '20-35cm', '8-15 years', '38-44°C basking', '28-32°C', '24-26°C', '20-23°C', '20-40%', '120x60x60cm', 'Sand, rocks essential', '12h cycle, UVB 10-12% required', 'Insects + occasional small vertebrates', 'Every other day', 'Insect 1/2 head width', 'Can be handled with patience', 'Diurnal, active, can run bipedally', 'MBD without UVB', 'Stress, refused feeding', 'intermediate'),

('lizard-curly-tail', 'Curly-Tail Lizard', 'Leiocephalus carinatus', 'lizard', 'Caribbean', '20-25cm', '5-7 years', '34-38°C', '26-30°C', '22-24°C', '20-22°C', '40-60%', '90x45x45cm', 'Sand, leaf litter', '12h cycle, UVB 10-12% required', 'Insects + occasional plants', 'Every other day', 'Insect 1/2 head width', 'Avoid handling, flighty', 'Diurnal, active', 'MBD, dehydration', 'Stress, refused feeding', 'intermediate'),

('basilisk-green', 'Green Basilisk', 'Basiliscus plumifrons', 'lizard', 'Central America', '60-80cm', '8-12 years', '32-35°C', '27-30°C', '23-26°C', '22-24°C', '70-80%', 'Tall 120x60x150cm', 'Coco fibre, branches, water feature', '12h cycle, UVB 10-12% required', 'Insects, small vertebrates, fruit', 'Daily juvenile, every other day adult', 'Insect 1/2 head width', 'Avoid handling, very skittish', 'Active, runs on water (the "Jesus lizard")', 'MBD, dehydration, injuries from flight', 'Stress, refused feeding', 'advanced'),

('tegu-red', 'Red Tegu', 'Salvator rufescens', 'lizard', 'Argentina, Paraguay', '90-120cm', '15-20 years', '38-42°C', '28-32°C', '24-26°C', '22-24°C', '50-60%', 'Massive: 240x90x90cm for adult', 'Cypress, topsoil mix', '12h cycle, UVB 10-12% required', 'Insects, rodents, fruit, eggs, occasionally raw meat', 'Daily juvenile, 2-3x weekly adult', 'Varies — omnivorous', 'Can be very tame with handling from young', 'Diurnal, intelligent, dog-like personality', 'Obesity, MBD without UVB', 'Aggression if not socialized', 'advanced'),

('tegu-gold', 'Gold Tegu', 'Tupinambis teguixin', 'lizard', 'South America (Amazon basin)', '90-120cm', '12-15 years', '38-42°C', '28-32°C', '24-26°C', '22-24°C', '60-70%', 'Massive enclosure 240x90x90cm', 'Cypress, topsoil', '12h cycle, UVB 10-12% required', 'Omnivorous: insects, rodents, fruit, eggs', 'Daily juvenile, 2-3x weekly adult', 'Varies', 'Less tractable than black-and-white tegu', 'Alert, can be defensive', 'Obesity, MBD', 'Aggression with poor handling', 'advanced'),

('monitor-nile', 'Nile Monitor', 'Varanus niloticus', 'lizard', 'Sub-Saharan Africa, SA native', '1.5-2m', '15-20 years', '40-45°C', '30-34°C', '24-27°C', '22-24°C', '60-70%', 'Massive: 360x180x180cm for adult', 'Cypress, topsoil mix, deep substrate', '12h cycle, UVB 10-12% required', 'Rodents, fish, insects, eggs, chicken', 'Daily juvenile, 2x weekly adult', 'Varies', 'Generally too aggressive for handling, expert keepers', 'Powerful, intelligent, often nippy', 'Obesity, MBD', 'Aggression, escape attempts', 'expert'),

('monitor-emerald-tree', 'Emerald Tree Monitor', 'Varanus prasinus', 'lizard', 'New Guinea', '70-100cm', '10-15 years', '32-35°C', '28-30°C', '24-26°C', '22-24°C', '70-85%', 'Tall arboreal 120x60x180cm', 'Coco fibre, branches', '12h cycle, UVB 10-12% required', 'Insects, small vertebrates', 'Every other day', 'Varies', 'Avoid handling, arboreal and shy', 'Arboreal, social, prehensile tail', 'MBD, RI, dehydration', 'Stress, refused feeding', 'expert'),

('skink-fire', 'Fire Skink', 'Lepidothyris fernandi', 'lizard', 'West Africa', '25-35cm', '15-20 years', '30-32°C', '26-28°C', '22-24°C', '20-22°C', '60-80%', '120x45x45cm', 'Cypress, topsoil, leaf litter, burrowing depth', '12h cycle, UVB 5-6% required', 'Insects + occasional fruit', 'Every other day', 'Insect 1/2 head width', 'Generally skittish, can tame with patience', 'Diurnal, semi-fossorial, brightly colored', 'MBD, RI', 'Stress, refused feeding', 'intermediate'),

('skink-monkey-tail', 'Monkey-Tailed Skink', 'Corucia zebrata', 'lizard', 'Solomon Islands', '60-80cm', '20-25 years', '28-30°C', '24-27°C', '20-23°C', '18-21°C', '60-80%', 'Tall arboreal 120x60x180cm', 'Cypress, branches, foliage', '12h cycle, UVB 5-6% required', 'HERBIVORE: leafy greens, fruits, vegetables', 'Daily', 'Plant matter', 'Bonds with one person, can be defensive otherwise', 'Arboreal, prehensile tail, only viviparous skink', 'MBD without UVB', 'Stress, refused feeding', 'advanced'),

('skink-prehensile-tailed-cape', 'Cape Skink', 'Trachylepis capensis', 'lizard', 'Southern Africa, SA native', '15-25cm', '8-10 years', '32-34°C', '26-29°C', '22-25°C', '20-23°C', '40-60%', '90x45x45cm', 'Sand mix, leaf litter', '12h cycle, UVB 5-6% recommended', 'Insects + occasional fruit', 'Every other day', 'Insect 1/2 head width', 'Tolerates handling, hardy', 'Diurnal, active, common SA species', 'MBD, parasites', 'Stuck sheds, refused feeding', 'beginner'),

('skink-five-lined', 'Five-Lined Skink', 'Plestiodon fasciatus', 'lizard', 'Eastern USA', '12-22cm', '5-10 years', '32-34°C', '25-28°C', '20-23°C', '18-21°C', '50-70%', '60x45x45cm', 'Coco fibre, leaf litter', '12h cycle, UVB 5-6% required', 'Small insects', 'Every other day', 'Small insects', 'Avoid handling, drops tail easily', 'Diurnal, active, juveniles have blue tail', 'MBD, RI', 'Stress, lost tails', 'intermediate'),

('lizard-anole-brown', 'Brown Anole', 'Anolis sagrei', 'lizard', 'Caribbean, Florida', '10-20cm', '4-8 years', '30-32°C', '24-28°C', '20-23°C', '18-21°C', '50-70%', '45x45x60cm', 'Coco fibre, plants', '12h cycle, UVB 5-6% required', 'Small insects', 'Daily', 'Tiny insects', 'Avoid handling, very flighty', 'Active, territorial males', 'MBD, dehydration', 'Stress, refused feeding', 'beginner'),

-- ============================================
-- ADDITIONAL GECKOS
-- ============================================
('gecko-leachianus', 'Leachianus Gecko', 'Rhacodactylus leachianus', 'gecko', 'New Caledonia', '30-40cm', '20-30 years', '24-28°C', '22-26°C', '20-23°C', '18-21°C', '60-80%', 'Tall 60x60x90cm', 'Coco fibre, large hides, branches', '12h cycle, UVB 2-5% optional', 'CGD (Pangea, Repashy) + insects', 'Every 2-3 days', 'CGD ad lib, insect 1/2 head', 'Can be defensive — "screaming" vocalizations', 'Largest gecko species, territorial', 'MBD if poor diet', 'Stress bites, refused feeding', 'intermediate'),

('gecko-chahoua', 'Chahoua Gecko / Mossy Prehensile-Tailed', 'Mniarogekko chahoua', 'gecko', 'New Caledonia', '20-25cm', '15-20 years', '24-28°C', '22-25°C', '19-22°C', '18-20°C', '60-80%', 'Tall 45x45x60cm', 'Coco fibre, branches, foliage', '12h cycle, UVB 2-5% optional', 'CGD + insects', 'Every 2-3 days', 'CGD ad lib, insect 1/2 head', 'Tolerates handling, less skittish than crested', 'Arboreal, prehensile tail, calm', 'MBD if poor diet', 'Stress, refused feeding', 'intermediate'),

('gecko-eyelash-banded', 'Banded Eyelash Gecko', 'Coleonyx mitratus', 'gecko', 'Central America', '12-18cm', '8-12 years', '28-30°C', '25-27°C', '22-24°C', '20-22°C', '50-70%', '45x30x30cm', 'Coco fibre, leaf litter, hides', '12h cycle, UVB 2-5% optional', 'Small insects', 'Every other day', 'Insect 1/2 head width', 'Nocturnal, can be handled briefly', 'Calm, nocturnal terrestrial', 'MBD if poor diet', 'Stress, refused feeding', 'intermediate'),

('gecko-cave', 'Banded Cave Gecko', 'Goniurosaurus luii', 'gecko', 'Southern China, Vietnam', '15-20cm', '8-10 years', '24-26°C', '20-23°C', '18-20°C', '16-19°C', '60-80%', '60x45x45cm', 'Coco fibre, slate caves, leaf litter', '12h cycle, NO direct UVB (cave dwellers)', 'Insects: crickets, dubia', 'Every 3-4 days', 'Insect 1/2 head width', 'Avoid handling, sensitive', 'Nocturnal, cool-living, slow', 'Heat stress, dehydration', 'Heat-related death', 'advanced'),

('gecko-knob-tailed', 'Knob-Tailed Gecko', 'Nephrurus levis', 'gecko', 'Australia', '10-15cm', '8-12 years', '32-35°C', '26-30°C', '22-25°C', '20-22°C', '30-40%', '60x30x30cm', 'Sand, rocks', '12h cycle, UVB 5-6% optional', 'Small insects', 'Every other day', 'Small insects', 'Avoid handling, easily stressed', 'Nocturnal, desert species', 'MBD, dehydration', 'Stress, refused feeding', 'advanced'),

('gecko-giant-day', 'Giant Day Gecko', 'Phelsuma grandis', 'gecko', 'Madagascar', '25-30cm', '10-15 years', '28-32°C', '24-27°C', '22-24°C', '20-22°C', '60-80%', 'Tall 60x60x90cm', 'Coco fibre, bamboo, plants', '12h cycle, UVB 5-10% essential', 'CGD + insects, occasional fruit', 'Daily', 'CGD ad lib, insect 1/2 head', 'Avoid handling — fragile skin', 'Diurnal, bright green, territorial', 'MBD without UVB', 'Tail drops, skin tears', 'intermediate'),

('gecko-tokay-blue', 'Electric Blue Day Gecko', 'Lygodactylus williamsi', 'gecko', 'Tanzania', '7-10cm', '5-10 years', '28-30°C', '24-27°C', '22-24°C', '20-22°C', '60-80%', '30x30x45cm', 'Coco fibre, bamboo, plants', '12h cycle, UVB 5-6% essential', 'Tiny insects + CGD', 'Daily', 'Tiny insects', 'Avoid handling — tiny and fragile', 'Diurnal, brilliant blue males', 'MBD without UVB', 'Stress, refused feeding', 'advanced'),

('gecko-flying-malayan', 'Malayan Flying Gecko', 'Gekko kuhli', 'gecko', 'Southeast Asia', '15-20cm', '8-10 years', '28-30°C', '24-27°C', '22-24°C', '20-22°C', '60-80%', 'Tall 60x60x90cm', 'Coco fibre, branches', '12h cycle, UVB 2-5% optional', 'Insects: crickets, roaches', 'Every other day', 'Insect 1/2 head width', 'Avoid handling, skittish', 'Nocturnal, arboreal, glides via skin flaps', 'Skin damage from handling', 'Stress, refused feeding', 'advanced'),

('gecko-leopard-african-fat-tail-mix', 'White-Lined Gecko', 'Gekko vittatus', 'gecko', 'Indonesia, Philippines', '20-25cm', '8-12 years', '28-32°C', '25-28°C', '22-24°C', '20-22°C', '60-80%', '60x45x60cm', 'Coco fibre, branches', '12h cycle, UVB 2-5% optional', 'Insects: crickets, roaches', 'Every other day', 'Insect 1/2 head width', 'Can be handled with patience', 'Nocturnal, arboreal', 'MBD, RI', 'Stress, refused feeding', 'intermediate'),

('gecko-leaf-tailed-satanic', 'Satanic Leaf-Tailed Gecko', 'Uroplatus phantasticus', 'gecko', 'Madagascar', '8-15cm', '8-10 years', '24-26°C', '20-23°C', '18-20°C', '16-19°C', '70-85%', 'Tall 45x45x60cm', 'Coco fibre, branches, live plants', '12h cycle, UVB 2-5% required', 'Small insects', 'Every other day', 'Small insects', 'Avoid handling — extremely fragile', 'Nocturnal, master of camouflage', 'Dehydration, heat stress', 'Stress death common', 'expert'),

('gecko-leaf-tailed-mossy', 'Mossy Leaf-Tailed Gecko', 'Uroplatus sikorae', 'gecko', 'Madagascar', '15-20cm', '8-10 years', '24-26°C', '20-23°C', '18-20°C', '16-19°C', '70-85%', 'Tall 60x60x90cm', 'Coco fibre, branches, live plants', '12h cycle, UVB 2-5% required', 'Crickets, dubia', 'Every other day', 'Insect 1/2 head width', 'Avoid handling — fragile, stressed easily', 'Nocturnal, exceptional camouflage', 'Heat stress, dehydration', 'Stress, refused feeding', 'expert'),

('gecko-pygmy-cape', 'Cape Dwarf Gecko', 'Lygodactylus capensis', 'gecko', 'Southern Africa, SA native', '6-9cm', '5-8 years', '28-30°C', '25-28°C', '22-24°C', '20-22°C', '50-70%', '30x30x45cm', 'Coco fibre, bamboo', '12h cycle, UVB 5-6% essential', 'Tiny insects (fruit flies, pinhead crickets)', 'Daily', 'Tiny insects', 'Avoid handling — tiny and fragile', 'Diurnal, often kept as colony', 'MBD without UVB', 'Stress, escape', 'intermediate'),

('gecko-pictus', 'Pictus Gecko', 'Paroedura pictus', 'gecko', 'Madagascar', '12-18cm', '8-15 years', '28-30°C', '24-27°C', '22-24°C', '20-22°C', '50-70%', '60x30x30cm', 'Coco fibre, sand mix', '12h cycle, UVB 2-5% optional', 'Insects: crickets, roaches', 'Every other day', 'Insect 1/2 head width', 'Tolerates handling, calm', 'Nocturnal, terrestrial, hardy', 'MBD, dehydration', 'Stress, refused feeding', 'beginner'),

-- ============================================
-- ADDITIONAL TORTOISES & TURTLES
-- ============================================
('tortoise-marginated', 'Marginated Tortoise', 'Testudo marginata', 'tortoise', 'Greece, Italy', '30-40cm', '50-100 years', '32-35°C', '25-28°C', '20-23°C', '15-18°C', '40-60%', 'Outdoor 4x2m+ or large indoor', 'Topsoil, hay, coco coir', '12h cycle, UVB 10-12% required', 'Leafy greens, grass, weeds, hay', 'Daily', 'Plant matter, varied', 'Tolerates handling but stresses if frequent', 'Diurnal, hardy', 'MBD, shell pyramiding', 'Pyramiding from poor diet', 'intermediate'),

('tortoise-pancake', 'Pancake Tortoise', 'Malacochersus tornieri', 'tortoise', 'East Africa', '15-18cm', '25-35 years', '32-35°C', '26-29°C', '22-25°C', '20-22°C', '40-60%', '120x60x45cm', 'Sand, rocks (climber!)', '12h cycle, UVB 10-12% required', 'Greens, grass, weeds', 'Daily', 'Plant matter', 'Tolerates handling, flat shell unique', 'Diurnal, agile rock climber', 'MBD, shell issues', 'Pyramiding, escape attempts', 'intermediate'),

('tortoise-egyptian', 'Egyptian Tortoise', 'Testudo kleinmanni', 'tortoise', 'Egypt, Libya (CITES protected)', '10-15cm', '70-100 years', '32-35°C', '24-28°C', '20-22°C', '15-18°C', '30-50%', '120x60x45cm', 'Sand, hay', '12h cycle, UVB 10-12% required', 'Grass, weeds, leafy greens', 'Daily', 'Plant matter', 'Avoid frequent handling — sensitive', 'Diurnal, smallest tortoise species', 'MBD, RI', 'CITES paperwork required', 'advanced'),

('turtle-red-eared-slider', 'Red-Eared Slider', 'Trachemys scripta elegans', 'tortoise', 'Southern USA, now invasive', '20-30cm', '30-50 years', '32-35°C basking', '24-27°C water', '22-24°C water', '22-24°C water', '60-80%', 'Aquarium: 100L+ per slider', 'Filter, basking platform', '12h cycle, UVB 10-12% required', 'Pellets, leafy greens, insects, fish', 'Daily juvenile, every 2-3 days adult', 'Varies', 'Tolerates handling but messy aquatic', 'Aquatic turtle, very common pet', 'Shell rot, MBD, RI', 'Pyramiding, shell infections', 'beginner'),

('turtle-musk-stinkpot', 'Common Musk Turtle (Stinkpot)', 'Sternotherus odoratus', 'tortoise', 'Eastern USA', '8-13cm', '30-50 years', '28-30°C basking', '22-25°C water', '20-22°C water', '20-22°C water', '60-80%', 'Aquarium: 75L+', 'Filter, sand or bare', '12h cycle, UVB 5-10% required', 'Pellets, insects, fish', 'Every other day', 'Varies', 'Can be nippy when handled', 'Aquatic, mostly bottom-dwelling', 'Shell rot, MBD', 'Aggression with same-sex tankmates', 'beginner'),

('turtle-painted', 'Painted Turtle', 'Chrysemys picta', 'tortoise', 'North America', '15-25cm', '25-40 years', '32-35°C basking', '22-26°C water', '20-22°C water', '20-22°C water', '60-80%', 'Aquarium: 200L+ adult', 'Filter, basking platform', '12h cycle, UVB 10-12% required', 'Pellets, greens, insects', 'Daily juvenile, every 2 days adult', 'Varies', 'Tolerates brief handling', 'Aquatic, basks heavily', 'Shell rot, MBD', 'Pyramiding, fungal issues', 'beginner'),

('turtle-african-sideneck', 'African Sideneck Turtle', 'Pelusios castaneus', 'tortoise', 'Sub-Saharan Africa', '15-22cm', '20-30 years', '30-32°C basking', '24-27°C water', '22-24°C water', '22-24°C water', '70-85%', 'Aquarium: 200L+', 'Filter, basking spot', '12h cycle, UVB 5-10% required', 'Pellets, insects, fish, greens', 'Every other day', 'Varies', 'Tolerates handling', 'Aquatic, retracts head sideways', 'Shell rot, RI', 'Stuck shedding scutes', 'intermediate'),

('tortoise-spider', 'Spider Tortoise', 'Pyxis arachnoides', 'tortoise', 'Madagascar (CITES protected)', '12-15cm', '50-70 years', '30-32°C', '24-27°C', '20-23°C', '18-21°C', '60-80%', '120x60x45cm', 'Coco coir, sand mix', '12h cycle, UVB 10-12% required', 'Leafy greens, weeds, occasional fruit', 'Daily', 'Plant matter', 'Avoid frequent handling', 'Diurnal, requires brumation', 'MBD, RI', 'Sensitive husbandry', 'advanced'),

('tortoise-indian-star', 'Indian Star Tortoise', 'Geochelone elegans', 'tortoise', 'India, Sri Lanka', '20-30cm', '50-80 years', '32-35°C', '24-28°C', '22-25°C', '20-23°C', '40-70%', '180x90x60cm minimum', 'Coco coir, hay', '12h cycle, UVB 10-12% required', 'Grasses, hay, greens, weeds', 'Daily', 'Plant matter', 'Avoid frequent handling — stresses', 'Diurnal, beautiful star pattern', 'MBD, RI, pyramiding', 'Pyramiding from low humidity diet errors', 'advanced'),

-- ============================================
-- AMPHIBIANS (category 'other')
-- ============================================
('frog-pacman', 'Pacman Frog', 'Ceratophrys ornata', 'other', 'Argentina, Uruguay', '10-18cm', '10-15 years', '24-26°C', '22-24°C', '20-22°C', '18-20°C', '60-80%', '45x30x30cm (single)', 'Coco fibre, moisture-holding', '12h cycle, low UVB optional', 'Insects, occasional pinky mice', 'Juvenile: every 2-3 days. Adult: every 7-10 days', 'Insect 1/2 head width', 'Minimal handling — absorb through skin', 'Sit-and-wait predator, will bite anything', 'Bloating, impaction from substrate', 'Overfeeding obesity', 'beginner'),

('frog-african-bullfrog', 'African Bullfrog', 'Pyxicephalus adspersus', 'other', 'Sub-Saharan Africa, SA native', '20-25cm (males)', '20-35 years', '26-28°C', '22-25°C', '20-22°C', '18-20°C', '60-80%', '90x45x45cm (single)', 'Coco fibre, hide for burrowing', '12h cycle, low UVB optional', 'Insects, rodents, fish', 'Every 7-10 days', 'Insect 1/2 head width or pinky', 'Avoid handling, will bite hard', 'Aggressive eater, calm otherwise', 'Bloating, impaction', 'Overfeeding obesity', 'intermediate'),

('frog-tomato', 'Tomato Frog', 'Dyscophus antongilii', 'other', 'Madagascar', '6-10cm', '6-8 years', '24-26°C', '22-25°C', '20-22°C', '18-20°C', '70-80%', '45x30x30cm', 'Coco fibre, sphagnum moss', '12h cycle, low UVB optional', 'Crickets, dubia, worms', 'Every 2-3 days', 'Small insects', 'Minimal handling — secretes sticky toxin when stressed', 'Calm, terrestrial, brilliant red', 'Bloating, impaction', 'Skin sensitivity', 'intermediate'),

('frog-fire-bellied', 'Fire-Bellied Toad', 'Bombina orientalis', 'other', 'Korea, China', '4-6cm', '15-20 years', '22-25°C', '20-23°C', '18-21°C', '16-19°C', '70-85%', '60x30x30cm with water section', 'Coco fibre + water area', '12h cycle, low UVB optional', 'Small insects', 'Every other day', 'Small insects', 'Minimal handling — mildly toxic skin', 'Diurnal, social, kept in groups', 'Bacterial infections', 'Skin issues from poor water quality', 'beginner'),

('frog-white-tree', 'White''s Tree Frog', 'Litoria caerulea', 'other', 'Australia, New Guinea', '8-12cm', '15-20 years', '26-28°C', '22-25°C', '20-22°C', '18-20°C', '60-70%', 'Tall 45x45x60cm', 'Coco fibre, branches, plants', '12h cycle, UVB 2-5% optional', 'Crickets, dubia, occasional pinky', 'Every 3-4 days', 'Insect 1/2 head width', 'Tolerates brief handling — large for tree frog', 'Calm, nocturnal arboreal', 'Obesity, bloat', 'Overfeeding common', 'beginner'),

('frog-red-eyed-tree', 'Red-Eyed Tree Frog', 'Agalychnis callidryas', 'other', 'Central America', '5-8cm', '5-10 years', '24-28°C', '22-25°C', '20-22°C', '18-20°C', '70-90%', 'Tall 45x45x60cm', 'Coco fibre, live plants', '12h cycle, UVB 2-5% optional', 'Small insects', 'Every 2-3 days', 'Small insects', 'Avoid handling — fragile skin', 'Nocturnal arboreal, brilliant colors', 'Bacterial infections, MBD', 'Skin sensitivity', 'intermediate'),

('frog-dart-blue', 'Blue Poison Dart Frog', 'Dendrobates tinctorius azureus', 'other', 'Suriname', '3-5cm', '10-15 years', '24-26°C', '22-25°C', '20-22°C', '18-20°C', '80-100%', 'Bioactive 45x45x45cm', 'Bioactive substrate with springtails', '12h cycle, UVB 2-5% optional', 'Fruit flies, springtails, pinhead crickets', 'Daily', 'Tiny insects', 'NEVER handle — even captive-bred secrete', 'Diurnal, social, captive-bred non-toxic', 'Bacterial issues', 'Sensitive to water quality', 'advanced'),

('frog-clawed-african', 'African Clawed Frog', 'Xenopus laevis', 'other', 'Sub-Saharan Africa, SA native', '10-15cm', '15-25 years', '20-24°C water', '20-24°C water', '20-24°C water', '20-24°C water', '100% (aquatic)', 'Aquarium 75L+', 'Bare or fine gravel, filter', '12h cycle, low UVB optional', 'Pellets, earthworms, bloodworms', 'Every 2-3 days', 'Small items', 'Avoid handling — slippery and stressed', 'Fully aquatic, hardy', 'Bloat, dropsy', 'Overfeeding', 'beginner'),

('axolotl', 'Axolotl', 'Ambystoma mexicanum', 'other', 'Mexico (Lake Xochimilco)', '20-30cm', '10-15 years', '16-18°C water', '16-18°C water', '14-18°C water', '14-18°C water', '100% (aquatic)', 'Aquarium 75L+ per axolotl', 'Bare bottom or fine sand only', 'Low light, NO UVB needed', 'Bloodworms, earthworms, pellets', 'Daily juvenile, every 2-3 days adult', 'Bite-sized items', 'Minimal handling — slimy and stressed', 'Aquatic salamander, neotenic', 'Bloat, ammonia poisoning', 'Impaction from gravel', 'intermediate'),

-- ============================================
-- INVERTEBRATES (category 'other')
-- ============================================
('tarantula-curly-hair', 'Curly Hair Tarantula', 'Tliltocatl albopilosus', 'other', 'Central America', '12-15cm legspan', '20-30 years (female)', '24-28°C', '22-25°C', '20-22°C', '18-20°C', '60-75%', '30x30x20cm adult', 'Coco fibre, deep enough to burrow', 'Low light, no UVB', 'Crickets, dubia, occasional pinky', 'Every 7-14 days', 'Insect 1/2 body size', 'Calm species but never directly handle — bite/hairs', 'New World, urticating hairs', 'Dehydration, mites', 'Falling damage from height', 'beginner'),

('tarantula-mexican-red-knee', 'Mexican Red-Knee Tarantula', 'Brachypelma hamorii', 'other', 'Mexico', '12-14cm legspan', '25-30 years', '25-28°C', '22-25°C', '20-23°C', '18-21°C', '60-70%', '30x30x20cm', 'Coco fibre', 'Low light, no UVB', 'Crickets, dubia', 'Every 7-14 days', 'Insect 1/2 body size', 'Calm but uses urticating hairs', 'New World, slow, beautiful colors', 'Dehydration, falls', 'Falling damage', 'beginner'),

('tarantula-pink-toe', 'Pink-Toe Tarantula', 'Avicularia avicularia', 'other', 'South America', '12-15cm legspan', '8-12 years', '24-28°C', '22-26°C', '20-23°C', '18-21°C', '70-85%', 'Tall arboreal 30x30x45cm', 'Coco fibre, branches, plants', 'Low light, no UVB', 'Crickets, flies', 'Every 7-10 days', 'Insect 1/2 body size', 'Skittish, can jump — never handle', 'Arboreal, faster than terrestrials', 'Stuck molts, dehydration', 'Sudden death syndrome', 'intermediate'),

('scorpion-emperor', 'Emperor Scorpion', 'Pandinus imperator', 'other', 'West Africa', '15-20cm', '6-8 years', '26-28°C', '24-26°C', '22-24°C', '20-22°C', '70-85%', '60x30x30cm', 'Coco fibre, deep enough to burrow', 'Low light, no UVB', 'Crickets, dubia, mealworms', 'Every 7-14 days', 'Insect 1/2 body size', 'Mild venom but pinch hurts — minimal handling', 'CITES protected, social in groups', 'Dehydration, mold', 'Mold from over-misting', 'beginner'),

('scorpion-flat-rock', 'Flat Rock Scorpion', 'Hadogenes troglodytes', 'other', 'Southern Africa, SA native', '15-21cm', '20-25 years', '28-30°C', '24-27°C', '22-24°C', '20-22°C', '40-60%', '60x30x30cm', 'Sand mix with slate stacks', 'Low light, no UVB', 'Crickets, dubia', 'Every 14 days', 'Insect 1/2 body size', 'Mild venom — avoid handling', 'Longest-living scorpion species', 'Dehydration', 'Mold from too much humidity', 'intermediate'),

('millipede-african-giant', 'African Giant Black Millipede', 'Archispirostreptus gigas', 'other', 'East Africa', '20-30cm', '5-10 years', '24-26°C', '22-25°C', '20-22°C', '18-20°C', '70-85%', '60x30x30cm', 'Coco fibre, leaf litter, rotting wood', 'Low light, no UVB', 'Fruit, vegetables, fish flakes', 'Every 2-3 days', 'Plant matter', 'Can be handled but secretes irritant', 'Detritivore, calm', 'Mites, dehydration', 'Skin irritation if handled with sweat', 'beginner'),

('snail-giant-african-land', 'Giant African Land Snail', 'Achatina fulica', 'other', 'East Africa', '15-20cm shell', '5-10 years', '24-26°C', '22-25°C', '20-22°C', '18-20°C', '70-85%', '45x30x30cm', 'Coco fibre, leaf litter', 'Low light, no UVB', 'Vegetables, fruit, calcium', 'Daily', 'Plant matter', 'Can be handled gently', 'Hermaphrodite, ILLEGAL in many countries — check local laws', 'Shell issues from low calcium', 'Mites, parasites', 'beginner'),

('mantis-orchid', 'Orchid Mantis', 'Hymenopus coronatus', 'other', 'Southeast Asia', '4-7cm', '6-9 months', '26-28°C', '24-26°C', '20-22°C', '18-20°C', '60-80%', '30x30x45cm tall', 'Coco fibre, branches, flowers', 'Low light, no UVB', 'Flies, moths, occasional cricket', 'Every 2-3 days', 'Small insects', 'Can be handled briefly', 'Mimics flowers, beautiful', 'Short lifespan, molting issues', 'Dehydration during molt', 'intermediate');

-- Verify count
-- select count(*) from species;
